//! Rust library for the Oxide “counter” Flutter example.
//!
//! This crate exposes a small, FFI-friendly API surface used by the Flutter app.
//! The public types are primarily generated via `oxide_generator_rs` and
//! `flutter_rust_bridge`.

/// FFI-facing API surface for the Flutter example.
pub mod api;
mod state;
mod runtime;
mod frb_generated;

/// Application engine generated by the `#[reducer(...)]` macro.
pub use api::bridge::AppEngine;
/// Error type exposed across the FFI boundary.
pub use oxide_core::OxideError;
/// Result type used by the Rust-side API.
pub use oxide_core::{CoreResult, StateSnapshot};
/// Watch receiver type used for subscribing to state snapshots.
pub use tokio::sync::watch::Receiver;

#[cfg(test)]
mod tests;
