//! Rust library for the Oxide “todos” Flutter example.
//!
//! This example demonstrates validation, error handling, and optional state
//! persistence (when enabled by features on the Rust side).

/// FFI-facing API surface for the Flutter example.
pub mod api;
mod state;
mod runtime;
mod frb_generated;

/// Application engine generated by the `#[reducer(...)]` macro.
pub use api::bridge::AppEngine;
/// Error type exposed across the FFI boundary.
pub use oxide_core::OxideError;
/// Result type used by the Rust-side API.
pub use oxide_core::{CoreResult, StateSnapshot};
/// Public state type for this example.
pub use state::AppState;
/// Watch receiver type used for subscribing to state snapshots.
pub use tokio::sync::watch::Receiver;

#[cfg(test)]
mod tests;
