// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

///oxide:actions
///oxide:meta:{"kind":"actions","name":"AppAction","docs":[],"variants":[{"name":"Increment","docs":[],"fields":[]},{"name":"Decrement","docs":[],"fields":[]},{"name":"Reset","docs":[],"fields":[]}]}
enum AppAction { increment, decrement, reset }
