// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../config/enums/theme_type.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'actions.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

@freezed
sealed class SettingsAction with _$SettingsAction {
  const SettingsAction._();

  const factory SettingsAction.setTheme(Theme field0) = SettingsAction_SetTheme;
  const factory SettingsAction.setMainColor(String field0) =
      SettingsAction_SetMainColor;
  const factory SettingsAction.extractMainColor(String field0) =
      SettingsAction_ExtractMainColor;
  const factory SettingsAction.resetState() = SettingsAction_ResetState;
  const factory SettingsAction.openHome() = SettingsAction_OpenHome;
  const factory SettingsAction.openSettings() = SettingsAction_OpenSettings;
  const factory SettingsAction.openChannels() = SettingsAction_OpenChannels;
  const factory SettingsAction.openBackendMatrix() =
      SettingsAction_OpenBackendMatrix;
  const factory SettingsAction.pop() = SettingsAction_Pop;
}
