// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../config/enums/theme_type.dart';
import '../../frb_generated.dart';
import 'actions.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SettingsReducer`, `__OxideReducerMarker_SettingsReducer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `effect`, `from`, `infer_slices`, `init`, `reduce`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `decode_state_value`, `dispatch`, `encode_current_state`, `encode_state_value`, `new`, `subscribe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ArcSettingsEngine> createEngine() =>
    RustLib.instance.api.crateApiSettingsReducerCreateEngine();

Future<void> disposeEngine({required ArcSettingsEngine engine}) =>
    RustLib.instance.api.crateApiSettingsReducerDisposeEngine(engine: engine);

Stream<(String, String, String)> setupRustLogs() =>
    RustLib.instance.api.crateApiSettingsReducerSetupRustLogs();

Future<SettingsStateSnapshot> dispatch({
  required ArcSettingsEngine engine,
  required SettingsAction action,
}) => RustLib.instance.api.crateApiSettingsReducerDispatch(
  engine: engine,
  action: action,
);

Future<SettingsStateSnapshot> current({required ArcSettingsEngine engine}) =>
    RustLib.instance.api.crateApiSettingsReducerCurrent(engine: engine);

Stream<SettingsStateSnapshot> stateStream({
  required ArcSettingsEngine engine,
}) => RustLib.instance.api.crateApiSettingsReducerStateStream(engine: engine);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Arc < SettingsEngine >>>
abstract class ArcSettingsEngine implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< OxideError>>
abstract class OxideError implements RustOpaqueInterface {}

class SettingsStateSnapshot {
  final BigInt revision;
  final SettingsState state;
  final List<SettingsStateSlice> slices;

  const SettingsStateSnapshot({
    required this.revision,
    required this.state,
    required this.slices,
  });

  @override
  int get hashCode => revision.hashCode ^ state.hashCode ^ slices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state &&
          slices == other.slices;
}
