// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'routes.dart';
import 'routes/confirm_route.dart';
import 'routes/home_route.dart';
import 'routes/oxide_navigation.dart';
import 'routes/splash_route.dart';
import 'state/app_action.dart';
import 'state/app_state.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcAppEnginePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OxideErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcAppEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  );

  @protected
  OxideError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  );

  @protected
  ArcAppEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  );

  @protected
  ArcAppEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  );

  @protected
  OxideError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  );

  @protected
  RustStreamSink<AppStateSnapshot> dco_decode_StreamSink_app_state_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<OxideNavCommand> dco_decode_StreamSink_oxide_nav_command_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<(String, String, String)>
  dco_decode_StreamSink_record_string_string_string_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppAction dco_decode_app_action(dynamic raw);

  @protected
  AppState dco_decode_app_state(dynamic raw);

  @protected
  AppStateSlice dco_decode_app_state_slice(dynamic raw);

  @protected
  AppStateSnapshot dco_decode_app_state_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppAction dco_decode_box_autoadd_app_action(dynamic raw);

  @protected
  AppState dco_decode_box_autoadd_app_state(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ConfirmRoute dco_decode_box_autoadd_confirm_route(dynamic raw);

  @protected
  HomeRoute dco_decode_box_autoadd_home_route(dynamic raw);

  @protected
  RouteKind dco_decode_box_autoadd_route_kind(dynamic raw);

  @protected
  RoutePayload dco_decode_box_autoadd_route_payload(dynamic raw);

  @protected
  RouteUpdateContext dco_decode_box_autoadd_route_update_context(dynamic raw);

  @protected
  SplashRoute dco_decode_box_autoadd_splash_route(dynamic raw);

  @protected
  TickState dco_decode_box_autoadd_tick_state(dynamic raw);

  @protected
  TickerControlState dco_decode_box_autoadd_ticker_control_state(dynamic raw);

  @protected
  ConfirmRoute dco_decode_confirm_route(dynamic raw);

  @protected
  HomeRoute dco_decode_home_route(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AppStateSlice> dco_decode_list_app_state_slice(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoutePayload> dco_decode_list_route_payload(dynamic raw);

  @protected
  List<TickStateSlice> dco_decode_list_tick_state_slice(dynamic raw);

  @protected
  List<TickerControlStateSlice> dco_decode_list_ticker_control_state_slice(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  RouteKind? dco_decode_opt_box_autoadd_route_kind(dynamic raw);

  @protected
  RoutePayload? dco_decode_opt_box_autoadd_route_payload(dynamic raw);

  @protected
  OxideNavCommand dco_decode_oxide_nav_command(dynamic raw);

  @protected
  (String, String, String) dco_decode_record_string_string_string(dynamic raw);

  @protected
  RouteKind dco_decode_route_kind(dynamic raw);

  @protected
  RouteOperation dco_decode_route_operation(dynamic raw);

  @protected
  RoutePayload dco_decode_route_payload(dynamic raw);

  @protected
  RouteUpdateContext dco_decode_route_update_context(dynamic raw);

  @protected
  SplashRoute dco_decode_splash_route(dynamic raw);

  @protected
  TickState dco_decode_tick_state(dynamic raw);

  @protected
  TickStateSlice dco_decode_tick_state_slice(dynamic raw);

  @protected
  TickerControlState dco_decode_ticker_control_state(dynamic raw);

  @protected
  TickerControlStateSlice dco_decode_ticker_control_state_slice(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcAppEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  );

  @protected
  OxideError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  );

  @protected
  ArcAppEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  );

  @protected
  ArcAppEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  );

  @protected
  OxideError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AppStateSnapshot> sse_decode_StreamSink_app_state_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<OxideNavCommand> sse_decode_StreamSink_oxide_nav_command_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<(String, String, String)>
  sse_decode_StreamSink_record_string_string_string_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppAction sse_decode_app_action(SseDeserializer deserializer);

  @protected
  AppState sse_decode_app_state(SseDeserializer deserializer);

  @protected
  AppStateSlice sse_decode_app_state_slice(SseDeserializer deserializer);

  @protected
  AppStateSnapshot sse_decode_app_state_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppAction sse_decode_box_autoadd_app_action(SseDeserializer deserializer);

  @protected
  AppState sse_decode_box_autoadd_app_state(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ConfirmRoute sse_decode_box_autoadd_confirm_route(
    SseDeserializer deserializer,
  );

  @protected
  HomeRoute sse_decode_box_autoadd_home_route(SseDeserializer deserializer);

  @protected
  RouteKind sse_decode_box_autoadd_route_kind(SseDeserializer deserializer);

  @protected
  RoutePayload sse_decode_box_autoadd_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  RouteUpdateContext sse_decode_box_autoadd_route_update_context(
    SseDeserializer deserializer,
  );

  @protected
  SplashRoute sse_decode_box_autoadd_splash_route(SseDeserializer deserializer);

  @protected
  TickState sse_decode_box_autoadd_tick_state(SseDeserializer deserializer);

  @protected
  TickerControlState sse_decode_box_autoadd_ticker_control_state(
    SseDeserializer deserializer,
  );

  @protected
  ConfirmRoute sse_decode_confirm_route(SseDeserializer deserializer);

  @protected
  HomeRoute sse_decode_home_route(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AppStateSlice> sse_decode_list_app_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoutePayload> sse_decode_list_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  List<TickStateSlice> sse_decode_list_tick_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  List<TickerControlStateSlice> sse_decode_list_ticker_control_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  RouteKind? sse_decode_opt_box_autoadd_route_kind(
    SseDeserializer deserializer,
  );

  @protected
  RoutePayload? sse_decode_opt_box_autoadd_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  OxideNavCommand sse_decode_oxide_nav_command(SseDeserializer deserializer);

  @protected
  (String, String, String) sse_decode_record_string_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RouteKind sse_decode_route_kind(SseDeserializer deserializer);

  @protected
  RouteOperation sse_decode_route_operation(SseDeserializer deserializer);

  @protected
  RoutePayload sse_decode_route_payload(SseDeserializer deserializer);

  @protected
  RouteUpdateContext sse_decode_route_update_context(
    SseDeserializer deserializer,
  );

  @protected
  SplashRoute sse_decode_splash_route(SseDeserializer deserializer);

  @protected
  TickState sse_decode_tick_state(SseDeserializer deserializer);

  @protected
  TickStateSlice sse_decode_tick_state_slice(SseDeserializer deserializer);

  @protected
  TickerControlState sse_decode_ticker_control_state(
    SseDeserializer deserializer,
  );

  @protected
  TickerControlStateSlice sse_decode_ticker_control_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_state_snapshot_Sse(
    RustStreamSink<AppStateSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_oxide_nav_command_Sse(
    RustStreamSink<OxideNavCommand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_record_string_string_string_Sse(
    RustStreamSink<(String, String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_action(AppAction self, SseSerializer serializer);

  @protected
  void sse_encode_app_state(AppState self, SseSerializer serializer);

  @protected
  void sse_encode_app_state_slice(AppStateSlice self, SseSerializer serializer);

  @protected
  void sse_encode_app_state_snapshot(
    AppStateSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_action(
    AppAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_state(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_confirm_route(
    ConfirmRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_home_route(
    HomeRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_kind(
    RouteKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_payload(
    RoutePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_update_context(
    RouteUpdateContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_splash_route(
    SplashRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tick_state(
    TickState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ticker_control_state(
    TickerControlState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_confirm_route(ConfirmRoute self, SseSerializer serializer);

  @protected
  void sse_encode_home_route(HomeRoute self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_app_state_slice(
    List<AppStateSlice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_route_payload(
    List<RoutePayload> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tick_state_slice(
    List<TickStateSlice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ticker_control_state_slice(
    List<TickerControlStateSlice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_route_kind(
    RouteKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_route_payload(
    RoutePayload? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_oxide_nav_command(
    OxideNavCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string_string(
    (String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_route_kind(RouteKind self, SseSerializer serializer);

  @protected
  void sse_encode_route_operation(
    RouteOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_route_payload(RoutePayload self, SseSerializer serializer);

  @protected
  void sse_encode_route_update_context(
    RouteUpdateContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_splash_route(SplashRoute self, SseSerializer serializer);

  @protected
  void sse_encode_tick_state(TickState self, SseSerializer serializer);

  @protected
  void sse_encode_tick_state_slice(
    TickStateSlice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ticker_control_state(
    TickerControlState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ticker_control_state_slice(
    TickerControlStateSlice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  );
}
