// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'app_action.freezed.dart';

@freezed
sealed class AppAction with _$AppAction {
  const AppAction._();

  const factory AppAction.addTodo({required String title}) = AppAction_AddTodo;
  const factory AppAction.toggleTodo({required String id}) =
      AppAction_ToggleTodo;
  const factory AppAction.deleteTodo({required String id}) =
      AppAction_DeleteTodo;
}
