// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';
import 'api/isolated_channels_bridge.dart';
import 'api/navigation_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'isolated_channels_demo/channels.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state/app_action.dart';
import 'state/app_state.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiBridgeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1148113875;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_counter_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiIsolatedChannelsBridgeCounterDemoDialogConfirm({
    required String title,
  });

  Future<bool>
  crateApiIsolatedChannelsBridgeCounterDemoDialogConfirmViaFrbCallback({
    required String title,
    required FutureOr<bool> Function(String) dartConfirm,
  });

  Stream<CounterDemoDialogPendingRequest>
  crateApiIsolatedChannelsBridgeCounterDemoDialogRequestsStream();

  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDialogRespond({
    required BigInt id,
    required CounterDemoDialogResponse response,
  });

  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDuplexIncoming({
    required CounterDemoIn event,
  });

  Stream<CounterDemoOut>
  crateApiIsolatedChannelsBridgeCounterDemoDuplexOutgoingStream();

  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDuplexSend({
    required String text,
  });

  Stream<CounterDemoEvent>
  crateApiIsolatedChannelsBridgeCounterDemoEventsStream();

  Future<String?> crateApiIsolatedChannelsBridgeCounterDemoLastIncomingText();

  Future<ArcAppEngine> crateApiBridgeCreateEngine();

  Future<AppStateSnapshot> crateApiBridgeCurrent({
    required ArcAppEngine engine,
  });

  Future<AppStateSnapshot> crateApiBridgeDispatch({
    required ArcAppEngine engine,
    required AppAction action,
  });

  Future<void> crateApiBridgeDisposeEngine({required ArcAppEngine engine});

  Future<void> crateApiIsolatedChannelsBridgeEmitCounterDemoNotification({
    required String message,
  });

  Future<void> crateApiBridgeInitApp();

  Future<void> crateApiIsolatedChannelsBridgeInitIsolatedChannelsDemo();

  Future<void> crateApiNavigationBridgeInitNavigation();

  Future<void> crateApiBridgeInitOxide();

  Stream<String> crateApiNavigationBridgeOxideNavCommandsStream();

  Future<void> crateApiNavigationBridgeOxideNavEmitResult({
    required String ticket,
    required String resultJson,
  });

  Future<void> crateApiNavigationBridgeOxideNavSetCurrentRoute({
    required String kind,
    required String payloadJson,
  });

  Stream<AppStateSnapshot> crateApiBridgeStateStream({
    required ArcAppEngine engine,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcAppEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcAppEngine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArcAppEnginePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OxideChannelError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OxideChannelError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OxideChannelErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OxideError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OxideError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_OxideErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiIsolatedChannelsBridgeCounterDemoDialogConfirm({
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoDialogConfirmConstMeta,
        argValues: [title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDialogConfirmConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_dialog_confirm",
        argNames: ["title"],
      );

  @override
  Future<bool>
  crateApiIsolatedChannelsBridgeCounterDemoDialogConfirmViaFrbCallback({
    required String title,
    required FutureOr<bool> Function(String) dartConfirm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_DartFn_Inputs_String_Output_bool_AnyhowException(
            dartConfirm,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoDialogConfirmViaFrbCallbackConstMeta,
        argValues: [title, dartConfirm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDialogConfirmViaFrbCallbackConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_dialog_confirm_via_frb_callback",
        argNames: ["title", "dartConfirm"],
      );

  @override
  Stream<CounterDemoDialogPendingRequest>
  crateApiIsolatedChannelsBridgeCounterDemoDialogRequestsStream() {
    final sink = RustStreamSink<CounterDemoDialogPendingRequest>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_counter_demo_dialog_pending_request_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiIsolatedChannelsBridgeCounterDemoDialogRequestsStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDialogRequestsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_dialog_requests_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDialogRespond({
    required BigInt id,
    required CounterDemoDialogResponse response,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_box_autoadd_counter_demo_dialog_response(
            response,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoDialogRespondConstMeta,
        argValues: [id, response],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDialogRespondConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_dialog_respond",
        argNames: ["id", "response"],
      );

  @override
  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDuplexIncoming({
    required CounterDemoIn event,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_counter_demo_in(event, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoDuplexIncomingConstMeta,
        argValues: [event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDuplexIncomingConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_duplex_incoming",
        argNames: ["event"],
      );

  @override
  Stream<CounterDemoOut>
  crateApiIsolatedChannelsBridgeCounterDemoDuplexOutgoingStream() {
    final sink = RustStreamSink<CounterDemoOut>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_counter_demo_out_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiIsolatedChannelsBridgeCounterDemoDuplexOutgoingStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDuplexOutgoingStreamConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_duplex_outgoing_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiIsolatedChannelsBridgeCounterDemoDuplexSend({
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoDuplexSendConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoDuplexSendConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_duplex_send",
        argNames: ["text"],
      );

  @override
  Stream<CounterDemoEvent>
  crateApiIsolatedChannelsBridgeCounterDemoEventsStream() {
    final sink = RustStreamSink<CounterDemoEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_counter_demo_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiIsolatedChannelsBridgeCounterDemoEventsStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoEventsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_events_stream",
        argNames: ["sink"],
      );

  @override
  Future<String?> crateApiIsolatedChannelsBridgeCounterDemoLastIncomingText() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeCounterDemoLastIncomingTextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeCounterDemoLastIncomingTextConstMeta =>
      const TaskConstMeta(
        debugName: "counter_demo_last_incoming_text",
        argNames: [],
      );

  @override
  Future<ArcAppEngine> crateApiBridgeCreateEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiBridgeCreateEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeCreateEngineConstMeta =>
      const TaskConstMeta(debugName: "create_engine", argNames: []);

  @override
  Future<AppStateSnapshot> crateApiBridgeCurrent({
    required ArcAppEngine engine,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
            engine,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_state_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeCurrentConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeCurrentConstMeta =>
      const TaskConstMeta(debugName: "current", argNames: ["engine"]);

  @override
  Future<AppStateSnapshot> crateApiBridgeDispatch({
    required ArcAppEngine engine,
    required AppAction action,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
            engine,
            serializer,
          );
          sse_encode_box_autoadd_app_action(action, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_state_snapshot,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiBridgeDispatchConstMeta,
        argValues: [engine, action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeDispatchConstMeta => const TaskConstMeta(
    debugName: "dispatch",
    argNames: ["engine", "action"],
  );

  @override
  Future<void> crateApiBridgeDisposeEngine({required ArcAppEngine engine}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
            engine,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeDisposeEngineConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeDisposeEngineConstMeta =>
      const TaskConstMeta(debugName: "dispose_engine", argNames: ["engine"]);

  @override
  Future<void> crateApiIsolatedChannelsBridgeEmitCounterDemoNotification({
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeEmitCounterDemoNotificationConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeEmitCounterDemoNotificationConstMeta =>
      const TaskConstMeta(
        debugName: "emit_counter_demo_notification",
        argNames: ["message"],
      );

  @override
  Future<void> crateApiBridgeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiIsolatedChannelsBridgeInitIsolatedChannelsDemo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta:
            kCrateApiIsolatedChannelsBridgeInitIsolatedChannelsDemoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIsolatedChannelsBridgeInitIsolatedChannelsDemoConstMeta =>
      const TaskConstMeta(
        debugName: "init_isolated_channels_demo",
        argNames: [],
      );

  @override
  Future<void> crateApiNavigationBridgeInitNavigation() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiNavigationBridgeInitNavigationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavigationBridgeInitNavigationConstMeta =>
      const TaskConstMeta(debugName: "init_navigation", argNames: []);

  @override
  Future<void> crateApiBridgeInitOxide() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiBridgeInitOxideConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeInitOxideConstMeta =>
      const TaskConstMeta(debugName: "init_oxide", argNames: []);

  @override
  Stream<String> crateApiNavigationBridgeOxideNavCommandsStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 19,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData:
                sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
          ),
          constMeta: kCrateApiNavigationBridgeOxideNavCommandsStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiNavigationBridgeOxideNavCommandsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "oxide_nav_commands_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiNavigationBridgeOxideNavEmitResult({
    required String ticket,
    required String resultJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          sse_encode_String(resultJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiNavigationBridgeOxideNavEmitResultConstMeta,
        argValues: [ticket, resultJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavigationBridgeOxideNavEmitResultConstMeta =>
      const TaskConstMeta(
        debugName: "oxide_nav_emit_result",
        argNames: ["ticket", "resultJson"],
      );

  @override
  Future<void> crateApiNavigationBridgeOxideNavSetCurrentRoute({
    required String kind,
    required String payloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_String(payloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError,
        ),
        constMeta: kCrateApiNavigationBridgeOxideNavSetCurrentRouteConstMeta,
        argValues: [kind, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavigationBridgeOxideNavSetCurrentRouteConstMeta =>
      const TaskConstMeta(
        debugName: "oxide_nav_set_current_route",
        argNames: ["kind", "payloadJson"],
      );

  @override
  Stream<AppStateSnapshot> crateApiBridgeStateStream({
    required ArcAppEngine engine,
  }) {
    final sink = RustStreamSink<AppStateSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
              engine,
              serializer,
            );
            sse_encode_StreamSink_app_state_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiBridgeStateStreamConstMeta,
          argValues: [engine, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeStateStreamConstMeta => const TaskConstMeta(
    debugName: "state_stream",
    argNames: ["engine", "sink"],
  );

  Future<void> Function(int, dynamic)
  encode_DartFn_Inputs_String_Output_bool_AnyhowException(
    FutureOr<bool> Function(String) raw,
  ) {
    return (callId, rawArg0) async {
      final arg0 = dco_decode_String(rawArg0);

      Box<bool>? rawOutput;
      Box<AnyhowException>? rawError;
      try {
        rawOutput = Box(await raw(arg0));
      } catch (e, s) {
        rawError = Box(AnyhowException("$e\n\n$s"));
      }

      final serializer = SseSerializer(generalizedFrbRustBinding);
      assert((rawOutput != null) ^ (rawError != null));
      if (rawOutput != null) {
        serializer.buffer.putUint8(0);
        sse_encode_bool(rawOutput.value, serializer);
      } else {
        serializer.buffer.putUint8(1);
        sse_encode_AnyhowException(rawError!.value, serializer);
      }
      final output = serializer.intoRaw();

      generalizedFrbRustBinding.dartFnDeliverOutput(
        callId: callId,
        ptr: output.ptr,
        rustVecLen: output.rustVecLen,
        dataLen: output.dataLen,
      );
    };
  }

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcAppEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcAppEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OxideChannelError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OxideChannelError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_OxideError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_OxideError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ArcAppEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OxideChannelError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OxideChannelErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OxideError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OxideErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcAppEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FutureOr<bool> Function(String)
  dco_decode_DartFn_Inputs_String_Output_bool_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError('');
  }

  @protected
  Object dco_decode_DartOpaque(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return decodeDartOpaque(raw, generalizedFrbRustBinding);
  }

  @protected
  ArcAppEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OxideChannelError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OxideChannelErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  OxideError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OxideErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<AppStateSnapshot> dco_decode_StreamSink_app_state_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<CounterDemoDialogPendingRequest>
  dco_decode_StreamSink_counter_demo_dialog_pending_request_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<CounterDemoEvent> dco_decode_StreamSink_counter_demo_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<CounterDemoOut> dco_decode_StreamSink_counter_demo_out_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppAction dco_decode_app_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppAction_Increment();
      case 1:
        return AppAction_Decrement();
      case 2:
        return AppAction_Reset();
      case 3:
        return AppAction_OpenDetail();
      case 4:
        return AppAction_OpenConfirm(title: dco_decode_String(raw[1]));
      case 5:
        return AppAction_Pop();
      case 6:
        return AppAction_PopUntilHome();
      case 7:
        return AppAction_ResetStack();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AppState dco_decode_app_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppState(
      counter: dco_decode_u_64(arr[0]),
      lastConfirmed: dco_decode_opt_box_autoadd_bool(arr[1]),
    );
  }

  @protected
  AppStateSnapshot dco_decode_app_state_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppStateSnapshot(
      revision: dco_decode_u_64(arr[0]),
      state: dco_decode_app_state(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppAction dco_decode_box_autoadd_app_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_action(raw);
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CounterDemoDialogResponse dco_decode_box_autoadd_counter_demo_dialog_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_counter_demo_dialog_response(raw);
  }

  @protected
  CounterDemoIn dco_decode_box_autoadd_counter_demo_in(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_counter_demo_in(raw);
  }

  @protected
  CounterDemoDialogPendingRequest
  dco_decode_counter_demo_dialog_pending_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CounterDemoDialogPendingRequest(
      id: dco_decode_u_64(arr[0]),
      request: dco_decode_counter_demo_dialog_request(arr[1]),
    );
  }

  @protected
  CounterDemoDialogRequest dco_decode_counter_demo_dialog_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CounterDemoDialogRequest_Confirm(
          title: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CounterDemoDialogResponse dco_decode_counter_demo_dialog_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CounterDemoDialogResponse_Confirm(dco_decode_bool(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CounterDemoEvent dco_decode_counter_demo_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CounterDemoEvent_Notify(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CounterDemoIn dco_decode_counter_demo_in(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CounterDemoIn_Receive(text: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CounterDemoOut dco_decode_counter_demo_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CounterDemoOut_Send(text: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ArcAppEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OxideChannelError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OxideChannelErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OxideError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OxideErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcAppEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_isize(deserializer);
    return decodeDartOpaque(inner, generalizedFrbRustBinding);
  }

  @protected
  ArcAppEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcAppEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OxideChannelError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OxideChannelErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  OxideError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OxideErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<AppStateSnapshot> sse_decode_StreamSink_app_state_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<CounterDemoDialogPendingRequest>
  sse_decode_StreamSink_counter_demo_dialog_pending_request_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<CounterDemoEvent> sse_decode_StreamSink_counter_demo_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<CounterDemoOut> sse_decode_StreamSink_counter_demo_out_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppAction sse_decode_app_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AppAction_Increment();
      case 1:
        return AppAction_Decrement();
      case 2:
        return AppAction_Reset();
      case 3:
        return AppAction_OpenDetail();
      case 4:
        var var_title = sse_decode_String(deserializer);
        return AppAction_OpenConfirm(title: var_title);
      case 5:
        return AppAction_Pop();
      case 6:
        return AppAction_PopUntilHome();
      case 7:
        return AppAction_ResetStack();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AppState sse_decode_app_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_counter = sse_decode_u_64(deserializer);
    var var_lastConfirmed = sse_decode_opt_box_autoadd_bool(deserializer);
    return AppState(counter: var_counter, lastConfirmed: var_lastConfirmed);
  }

  @protected
  AppStateSnapshot sse_decode_app_state_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_revision = sse_decode_u_64(deserializer);
    var var_state = sse_decode_app_state(deserializer);
    return AppStateSnapshot(revision: var_revision, state: var_state);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppAction sse_decode_box_autoadd_app_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_action(deserializer));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  CounterDemoDialogResponse sse_decode_box_autoadd_counter_demo_dialog_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_counter_demo_dialog_response(deserializer));
  }

  @protected
  CounterDemoIn sse_decode_box_autoadd_counter_demo_in(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_counter_demo_in(deserializer));
  }

  @protected
  CounterDemoDialogPendingRequest
  sse_decode_counter_demo_dialog_pending_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_request = sse_decode_counter_demo_dialog_request(deserializer);
    return CounterDemoDialogPendingRequest(id: var_id, request: var_request);
  }

  @protected
  CounterDemoDialogRequest sse_decode_counter_demo_dialog_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_title = sse_decode_String(deserializer);
        return CounterDemoDialogRequest_Confirm(title: var_title);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CounterDemoDialogResponse sse_decode_counter_demo_dialog_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_bool(deserializer);
        return CounterDemoDialogResponse_Confirm(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CounterDemoEvent sse_decode_counter_demo_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_message = sse_decode_String(deserializer);
        return CounterDemoEvent_Notify(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CounterDemoIn sse_decode_counter_demo_in(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return CounterDemoIn_Receive(text: var_text);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CounterDemoOut sse_decode_counter_demo_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return CounterDemoOut_Send(text: var_text);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcAppEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    OxideChannelError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OxideChannelErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OxideErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcAppEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_DartFn_Inputs_String_Output_bool_AnyhowException(
    FutureOr<bool> Function(String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_DartOpaque(
      encode_DartFn_Inputs_String_Output_bool_AnyhowException(self),
      serializer,
    );
  }

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_isize(
      PlatformPointerUtil.ptrToPlatformInt64(
        encodeDartOpaque(
          self,
          portManager.dartHandlerPort,
          generalizedFrbRustBinding,
        ),
      ),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcAppEngine(
    ArcAppEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcAppEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    OxideChannelError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OxideChannelErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OxideErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_app_state_snapshot_Sse(
    RustStreamSink<AppStateSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_state_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_counter_demo_dialog_pending_request_Sse(
    RustStreamSink<CounterDemoDialogPendingRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_counter_demo_dialog_pending_request,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_counter_demo_event_Sse(
    RustStreamSink<CounterDemoEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_counter_demo_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_counter_demo_out_Sse(
    RustStreamSink<CounterDemoOut> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_counter_demo_out,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_action(AppAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppAction_Increment():
        sse_encode_i_32(0, serializer);
      case AppAction_Decrement():
        sse_encode_i_32(1, serializer);
      case AppAction_Reset():
        sse_encode_i_32(2, serializer);
      case AppAction_OpenDetail():
        sse_encode_i_32(3, serializer);
      case AppAction_OpenConfirm(title: final title):
        sse_encode_i_32(4, serializer);
        sse_encode_String(title, serializer);
      case AppAction_Pop():
        sse_encode_i_32(5, serializer);
      case AppAction_PopUntilHome():
        sse_encode_i_32(6, serializer);
      case AppAction_ResetStack():
        sse_encode_i_32(7, serializer);
    }
  }

  @protected
  void sse_encode_app_state(AppState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.counter, serializer);
    sse_encode_opt_box_autoadd_bool(self.lastConfirmed, serializer);
  }

  @protected
  void sse_encode_app_state_snapshot(
    AppStateSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.revision, serializer);
    sse_encode_app_state(self.state, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_action(
    AppAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_action(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_counter_demo_dialog_response(
    CounterDemoDialogResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_counter_demo_dialog_response(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_counter_demo_in(
    CounterDemoIn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_counter_demo_in(self, serializer);
  }

  @protected
  void sse_encode_counter_demo_dialog_pending_request(
    CounterDemoDialogPendingRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_counter_demo_dialog_request(self.request, serializer);
  }

  @protected
  void sse_encode_counter_demo_dialog_request(
    CounterDemoDialogRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CounterDemoDialogRequest_Confirm(title: final title):
        sse_encode_i_32(0, serializer);
        sse_encode_String(title, serializer);
    }
  }

  @protected
  void sse_encode_counter_demo_dialog_response(
    CounterDemoDialogResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CounterDemoDialogResponse_Confirm(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_bool(field0, serializer);
    }
  }

  @protected
  void sse_encode_counter_demo_event(
    CounterDemoEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CounterDemoEvent_Notify(message: final message):
        sse_encode_i_32(0, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_counter_demo_in(
    CounterDemoIn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CounterDemoIn_Receive(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
    }
  }

  @protected
  void sse_encode_counter_demo_out(
    CounterDemoOut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CounterDemoOut_Send(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
    }
  }

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ArcAppEngineImpl extends RustOpaque implements ArcAppEngine {
  // Not to be used by end users
  ArcAppEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcAppEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcAppEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcAppEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcAppEnginePtr,
  );
}

@sealed
class OxideChannelErrorImpl extends RustOpaque implements OxideChannelError {
  // Not to be used by end users
  OxideChannelErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OxideChannelErrorImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OxideChannelError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OxideChannelError,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_OxideChannelErrorPtr,
  );
}

@sealed
class OxideErrorImpl extends RustOpaque implements OxideError {
  // Not to be used by end users
  OxideErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OxideErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_OxideError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_OxideError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_OxideErrorPtr,
  );
}
