// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/isolated_channels_bridge.dart';
import 'api/settings/actions.dart';
import 'api/settings/dialogs.dart';
import 'api/settings/dialogs/__oxide_isolated_callback_dialog_service.dart';
import 'api/settings/reducer.dart';
import 'api/settings/side_effects.dart';
import 'api/settings/state.dart';
import 'config/enums/theme_type.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'isolated_channels_demo.dart';
import 'isolated_channels_demo/channels.dart';
import 'isolated_channels_demo/channels/__oxide_isolated_callback_showcase_demo_dialog.dart';
import 'isolated_channels_demo/channels/__oxide_isolated_duplex_showcase_demo_duplex.dart';
import 'isolated_channels_demo/channels/__oxide_isolated_duplex_showcase_demo_duplex/frb.dart';
import 'isolated_channels_demo/channels/__oxide_isolated_events_showcase_demo_events.dart';
import 'isolated_channels_demo/channels/__oxide_isolated_events_showcase_demo_events/frb.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'routes.dart';
import 'routes/backend_matrix_screen.dart';
import 'routes/channels_screen.dart';
import 'routes/home_screen.dart';
import 'routes/oxide_navigation.dart';
import 'routes/settings_screen.dart';
import 'routes/splash_screen.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcSettingsEnginePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OxideChannelErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OxideErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcSettingsEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    dynamic raw,
  );

  @protected
  OxideChannelError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    dynamic raw,
  );

  @protected
  OxideError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  );

  @protected
  ArcSettingsEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    dynamic raw,
  );

  @protected
  ArcSettingsEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    dynamic raw,
  );

  @protected
  OxideChannelError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    dynamic raw,
  );

  @protected
  OxideError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    dynamic raw,
  );

  @protected
  RustStreamSink<OxideNavCommand> dco_decode_StreamSink_oxide_nav_command_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<(String, String, String)>
  dco_decode_StreamSink_record_string_string_string_Sse(dynamic raw);

  @protected
  RustStreamSink<SettingsStateSnapshot>
  dco_decode_StreamSink_settings_state_snapshot_Sse(dynamic raw);

  @protected
  RustStreamSink<ShowcaseDemoDialogPendingRequest>
  dco_decode_StreamSink_showcase_demo_dialog_pending_request_Sse(dynamic raw);

  @protected
  RustStreamSink<ShowcaseDemoEvent>
  dco_decode_StreamSink_showcase_demo_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ShowcaseDemoOut> dco_decode_StreamSink_showcase_demo_out_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackendMatrixScreen dco_decode_backend_matrix_screen(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BackendMatrixScreen dco_decode_box_autoadd_backend_matrix_screen(dynamic raw);

  @protected
  ChannelsScreen dco_decode_box_autoadd_channels_screen(dynamic raw);

  @protected
  HomeScreen dco_decode_box_autoadd_home_screen(dynamic raw);

  @protected
  RouteKind dco_decode_box_autoadd_route_kind(dynamic raw);

  @protected
  RoutePayload dco_decode_box_autoadd_route_payload(dynamic raw);

  @protected
  RouteUpdateContext dco_decode_box_autoadd_route_update_context(dynamic raw);

  @protected
  SettingsAction dco_decode_box_autoadd_settings_action(dynamic raw);

  @protected
  SettingsScreen dco_decode_box_autoadd_settings_screen(dynamic raw);

  @protected
  SettingsState dco_decode_box_autoadd_settings_state(dynamic raw);

  @protected
  ShowcaseDemoDialogResponse
  dco_decode_box_autoadd_showcase_demo_dialog_response(dynamic raw);

  @protected
  ShowcaseDemoIn dco_decode_box_autoadd_showcase_demo_in(dynamic raw);

  @protected
  ShowcaseDemoOut dco_decode_box_autoadd_showcase_demo_out(dynamic raw);

  @protected
  SplashScreen dco_decode_box_autoadd_splash_screen(dynamic raw);

  @protected
  ChannelsScreen dco_decode_channels_screen(dynamic raw);

  @protected
  DialogService dco_decode_dialog_service(dynamic raw);

  @protected
  HomeScreen dco_decode_home_screen(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoutePayload> dco_decode_list_route_payload(dynamic raw);

  @protected
  List<SettingsStateSlice> dco_decode_list_settings_state_slice(dynamic raw);

  @protected
  List<ThemeSlice> dco_decode_list_theme_slice(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RouteKind? dco_decode_opt_box_autoadd_route_kind(dynamic raw);

  @protected
  RoutePayload? dco_decode_opt_box_autoadd_route_payload(dynamic raw);

  @protected
  OxideNavCommand dco_decode_oxide_nav_command(dynamic raw);

  @protected
  (String, String, String) dco_decode_record_string_string_string(dynamic raw);

  @protected
  RouteKind dco_decode_route_kind(dynamic raw);

  @protected
  RouteOperation dco_decode_route_operation(dynamic raw);

  @protected
  RoutePayload dco_decode_route_payload(dynamic raw);

  @protected
  RouteUpdateContext dco_decode_route_update_context(dynamic raw);

  @protected
  SettingsAction dco_decode_settings_action(dynamic raw);

  @protected
  SettingsScreen dco_decode_settings_screen(dynamic raw);

  @protected
  SettingsState dco_decode_settings_state(dynamic raw);

  @protected
  SettingsStateSlice dco_decode_settings_state_slice(dynamic raw);

  @protected
  SettingsStateSnapshot dco_decode_settings_state_snapshot(dynamic raw);

  @protected
  ShowcaseDemoDialog dco_decode_showcase_demo_dialog(dynamic raw);

  @protected
  ShowcaseDemoDialogPendingRequest
  dco_decode_showcase_demo_dialog_pending_request(dynamic raw);

  @protected
  ShowcaseDemoDialogRequest dco_decode_showcase_demo_dialog_request(
    dynamic raw,
  );

  @protected
  ShowcaseDemoDialogResponse dco_decode_showcase_demo_dialog_response(
    dynamic raw,
  );

  @protected
  ShowcaseDemoDuplex dco_decode_showcase_demo_duplex(dynamic raw);

  @protected
  ShowcaseDemoEvent dco_decode_showcase_demo_event(dynamic raw);

  @protected
  ShowcaseDemoEvents dco_decode_showcase_demo_events(dynamic raw);

  @protected
  ShowcaseDemoIn dco_decode_showcase_demo_in(dynamic raw);

  @protected
  ShowcaseDemoOut dco_decode_showcase_demo_out(dynamic raw);

  @protected
  SplashScreen dco_decode_splash_screen(dynamic raw);

  @protected
  Theme dco_decode_theme(dynamic raw);

  @protected
  ThemeSlice dco_decode_theme_slice(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcSettingsEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    SseDeserializer deserializer,
  );

  @protected
  OxideChannelError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    SseDeserializer deserializer,
  );

  @protected
  OxideError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  );

  @protected
  ArcSettingsEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    SseDeserializer deserializer,
  );

  @protected
  ArcSettingsEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    SseDeserializer deserializer,
  );

  @protected
  OxideChannelError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    SseDeserializer deserializer,
  );

  @protected
  OxideError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<OxideNavCommand> sse_decode_StreamSink_oxide_nav_command_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<(String, String, String)>
  sse_decode_StreamSink_record_string_string_string_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SettingsStateSnapshot>
  sse_decode_StreamSink_settings_state_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ShowcaseDemoDialogPendingRequest>
  sse_decode_StreamSink_showcase_demo_dialog_pending_request_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ShowcaseDemoEvent>
  sse_decode_StreamSink_showcase_demo_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<ShowcaseDemoOut> sse_decode_StreamSink_showcase_demo_out_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackendMatrixScreen sse_decode_backend_matrix_screen(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BackendMatrixScreen sse_decode_box_autoadd_backend_matrix_screen(
    SseDeserializer deserializer,
  );

  @protected
  ChannelsScreen sse_decode_box_autoadd_channels_screen(
    SseDeserializer deserializer,
  );

  @protected
  HomeScreen sse_decode_box_autoadd_home_screen(SseDeserializer deserializer);

  @protected
  RouteKind sse_decode_box_autoadd_route_kind(SseDeserializer deserializer);

  @protected
  RoutePayload sse_decode_box_autoadd_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  RouteUpdateContext sse_decode_box_autoadd_route_update_context(
    SseDeserializer deserializer,
  );

  @protected
  SettingsAction sse_decode_box_autoadd_settings_action(
    SseDeserializer deserializer,
  );

  @protected
  SettingsScreen sse_decode_box_autoadd_settings_screen(
    SseDeserializer deserializer,
  );

  @protected
  SettingsState sse_decode_box_autoadd_settings_state(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoDialogResponse
  sse_decode_box_autoadd_showcase_demo_dialog_response(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoIn sse_decode_box_autoadd_showcase_demo_in(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoOut sse_decode_box_autoadd_showcase_demo_out(
    SseDeserializer deserializer,
  );

  @protected
  SplashScreen sse_decode_box_autoadd_splash_screen(
    SseDeserializer deserializer,
  );

  @protected
  ChannelsScreen sse_decode_channels_screen(SseDeserializer deserializer);

  @protected
  DialogService sse_decode_dialog_service(SseDeserializer deserializer);

  @protected
  HomeScreen sse_decode_home_screen(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoutePayload> sse_decode_list_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingsStateSlice> sse_decode_list_settings_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  List<ThemeSlice> sse_decode_list_theme_slice(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RouteKind? sse_decode_opt_box_autoadd_route_kind(
    SseDeserializer deserializer,
  );

  @protected
  RoutePayload? sse_decode_opt_box_autoadd_route_payload(
    SseDeserializer deserializer,
  );

  @protected
  OxideNavCommand sse_decode_oxide_nav_command(SseDeserializer deserializer);

  @protected
  (String, String, String) sse_decode_record_string_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RouteKind sse_decode_route_kind(SseDeserializer deserializer);

  @protected
  RouteOperation sse_decode_route_operation(SseDeserializer deserializer);

  @protected
  RoutePayload sse_decode_route_payload(SseDeserializer deserializer);

  @protected
  RouteUpdateContext sse_decode_route_update_context(
    SseDeserializer deserializer,
  );

  @protected
  SettingsAction sse_decode_settings_action(SseDeserializer deserializer);

  @protected
  SettingsScreen sse_decode_settings_screen(SseDeserializer deserializer);

  @protected
  SettingsState sse_decode_settings_state(SseDeserializer deserializer);

  @protected
  SettingsStateSlice sse_decode_settings_state_slice(
    SseDeserializer deserializer,
  );

  @protected
  SettingsStateSnapshot sse_decode_settings_state_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoDialog sse_decode_showcase_demo_dialog(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoDialogPendingRequest
  sse_decode_showcase_demo_dialog_pending_request(SseDeserializer deserializer);

  @protected
  ShowcaseDemoDialogRequest sse_decode_showcase_demo_dialog_request(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoDialogResponse sse_decode_showcase_demo_dialog_response(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoDuplex sse_decode_showcase_demo_duplex(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoEvent sse_decode_showcase_demo_event(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoEvents sse_decode_showcase_demo_events(
    SseDeserializer deserializer,
  );

  @protected
  ShowcaseDemoIn sse_decode_showcase_demo_in(SseDeserializer deserializer);

  @protected
  ShowcaseDemoOut sse_decode_showcase_demo_out(SseDeserializer deserializer);

  @protected
  SplashScreen sse_decode_splash_screen(SseDeserializer deserializer);

  @protected
  Theme sse_decode_theme(SseDeserializer deserializer);

  @protected
  ThemeSlice sse_decode_theme_slice(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    ArcSettingsEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    OxideChannelError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    ArcSettingsEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    ArcSettingsEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    OxideChannelError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    OxideError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_oxide_nav_command_Sse(
    RustStreamSink<OxideNavCommand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_record_string_string_string_Sse(
    RustStreamSink<(String, String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_settings_state_snapshot_Sse(
    RustStreamSink<SettingsStateSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_showcase_demo_dialog_pending_request_Sse(
    RustStreamSink<ShowcaseDemoDialogPendingRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_showcase_demo_event_Sse(
    RustStreamSink<ShowcaseDemoEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_showcase_demo_out_Sse(
    RustStreamSink<ShowcaseDemoOut> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backend_matrix_screen(
    BackendMatrixScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_backend_matrix_screen(
    BackendMatrixScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_channels_screen(
    ChannelsScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_home_screen(
    HomeScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_kind(
    RouteKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_payload(
    RoutePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_route_update_context(
    RouteUpdateContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_action(
    SettingsAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_screen(
    SettingsScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_state(
    SettingsState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_showcase_demo_dialog_response(
    ShowcaseDemoDialogResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_showcase_demo_in(
    ShowcaseDemoIn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_showcase_demo_out(
    ShowcaseDemoOut self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_splash_screen(
    SplashScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channels_screen(
    ChannelsScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dialog_service(DialogService self, SseSerializer serializer);

  @protected
  void sse_encode_home_screen(HomeScreen self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_route_payload(
    List<RoutePayload> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_settings_state_slice(
    List<SettingsStateSlice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_theme_slice(
    List<ThemeSlice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_route_kind(
    RouteKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_route_payload(
    RoutePayload? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_oxide_nav_command(
    OxideNavCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string_string(
    (String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_route_kind(RouteKind self, SseSerializer serializer);

  @protected
  void sse_encode_route_operation(
    RouteOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_route_payload(RoutePayload self, SseSerializer serializer);

  @protected
  void sse_encode_route_update_context(
    RouteUpdateContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_action(
    SettingsAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_screen(
    SettingsScreen self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_state(SettingsState self, SseSerializer serializer);

  @protected
  void sse_encode_settings_state_slice(
    SettingsStateSlice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_state_snapshot(
    SettingsStateSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_dialog(
    ShowcaseDemoDialog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_dialog_pending_request(
    ShowcaseDemoDialogPendingRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_dialog_request(
    ShowcaseDemoDialogRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_dialog_response(
    ShowcaseDemoDialogResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_duplex(
    ShowcaseDemoDuplex self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_event(
    ShowcaseDemoEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_events(
    ShowcaseDemoEvents self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_in(
    ShowcaseDemoIn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_showcase_demo_out(
    ShowcaseDemoOut self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_splash_screen(SplashScreen self, SseSerializer serializer);

  @protected
  void sse_encode_theme(Theme self, SseSerializer serializer);

  @protected
  void sse_encode_theme_slice(ThemeSlice self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSettingsEngine(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideChannelError(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOxideError(
    int ptr,
  );
}
