// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'routes/backend_matrix_screen.dart';
import 'routes/channels_screen.dart';
import 'routes/home_screen.dart';
import 'routes/settings_screen.dart';
import 'routes/splash_screen.dart';
part 'routes.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_kind_and_payload`, `payload_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RouteInitContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_str`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `hash`, `into_payload`, `into_payload`, `into_payload`, `into_payload`, `into_payload`, `kind`

enum RouteKind {
  backendMatrixScreen,
  channelsScreen,
  homeScreen,
  settingsScreen,
  splashScreen;

  Future<void> asStr() =>
      RustLib.instance.api.crateRoutesRouteKindAsStr(that: this);

  static Future<RouteKind?> fromStr({required String s}) =>
      RustLib.instance.api.crateRoutesRouteKindFromStr(s: s);
}

enum RouteOperation { push, pop, popUntil, reset, sync_ }

@freezed
sealed class RoutePayload with _$RoutePayload {
  const RoutePayload._();

  const factory RoutePayload.backendMatrixScreen(BackendMatrixScreen field0) =
      RoutePayload_BackendMatrixScreen;
  const factory RoutePayload.channelsScreen(ChannelsScreen field0) =
      RoutePayload_ChannelsScreen;
  const factory RoutePayload.homeScreen(HomeScreen field0) =
      RoutePayload_HomeScreen;
  const factory RoutePayload.settingsScreen(SettingsScreen field0) =
      RoutePayload_SettingsScreen;
  const factory RoutePayload.splashScreen(SplashScreen field0) =
      RoutePayload_SplashScreen;

  Future<RouteKind> kind() =>
      RustLib.instance.api.crateRoutesRoutePayloadKind(that: this);
}

class RouteUpdateContext {
  final RouteOperation operation;
  final RoutePayload? route;
  final String? resultJson;
  final String? argumentsJson;
  final bool firstPush;

  const RouteUpdateContext({
    required this.operation,
    this.route,
    this.resultJson,
    this.argumentsJson,
    required this.firstPush,
  });

  @override
  int get hashCode =>
      operation.hashCode ^
      route.hashCode ^
      resultJson.hashCode ^
      argumentsJson.hashCode ^
      firstPush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteUpdateContext &&
          runtimeType == other.runtimeType &&
          operation == other.operation &&
          route == other.route &&
          resultJson == other.resultJson &&
          argumentsJson == other.argumentsJson &&
          firstPush == other.firstPush;
}
