import 'dart:convert';
import 'dart:io';

import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:glob/glob.dart';

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestShortStyleLanguageVersion,
  pageWidth: 100,
);

final class RustRouteFieldMeta {
  RustRouteFieldMeta({required this.name, required this.type});

  final String name;
  final String type;
}

final class RustRouteMeta {
  RustRouteMeta({
    required this.kind,
    required this.rustType,
    required this.path,
    required this.returnType,
    required this.extraType,
    required this.fields,
  });

  final String kind;
  final String rustType;
  final String? path;
  final String returnType;
  final String extraType;
  final List<RustRouteFieldMeta> fields;
}

final class RustRouteMetadata {
  RustRouteMetadata({required this.crateName, required this.routes});

  final String crateName;
  final List<RustRouteMeta> routes;
}

// ------------------ channel metadata (Phase3 support) ------------------

final class RustChannelMetadata {
  RustChannelMetadata({
    required this.events,
    required this.callbacks,
    this.crateName,
    this.initFnName,
  });

  final List<RustEventChannelMeta> events;
  final List<RustCallbackMeta> callbacks;

  /// The name of the Rust crate that produced the metadata (e.g.
  /// `isolated_channels_demo`).
  final String? crateName;

  /// If available, the name of the Dart initialization function exposed by
  /// `isolated_channels_bridge.dart`. The generator will call this helper
  /// when setting up channels inside `OxideStack.init`.
  ///
  /// Tests may supply this manually; during normal builds we attempt to parse
  /// the bridge file to figure it out automatically.
  final String? initFnName;
}

final class RustEventChannelMeta {
  RustEventChannelMeta({required this.name, required this.eventType});

  /// Rust struct identifier, e.g. `CounterDemoEvents`.
  final String name;

  /// Dart type exposed for events, typically an enum imported from the
  /// generated `rust/.../channels.dart` file.
  final String eventType;
}

final class RustCallbackMeta {
  RustCallbackMeta({
    required this.name,
    required this.requestType,
    required this.responseType,
  });

  final String name;
  final String requestType;
  final String responseType;
}

Future<RustChannelMetadata> readRustChannelMetadata() async {
  final dir = Directory('rust/target/oxide_channels');
  final events = <RustEventChannelMeta>[];
  final callbacks = <RustCallbackMeta>[];
  final crateNames = <String>{};

  if (dir.existsSync()) {
    final files = dir
        .listSync(followLinks: false)
        .whereType<File>()
        .where((f) => f.path.endsWith('.json'))
        .toList(growable: false);

    for (final file in files) {
      final jsonStr = await file.readAsString();
      final obj = jsonDecode(jsonStr);
      if (obj is! Map<String, dynamic>) continue;

      if (obj['crate_name'] is String) {
        crateNames.add(obj['crate_name'] as String);
      }

      final rawEvents = obj['events'];
      if (rawEvents is List) {
        for (final raw in rawEvents) {
          if (raw is! Map<String, dynamic>) continue;
          final name = raw['name'];
          final eventType = raw['event_type'];
          if (name is String && eventType is String) {
            events.add(RustEventChannelMeta(name: name, eventType: eventType));
          }
        }
      }

      final rawCallbacks = obj['callbacks'];
      if (rawCallbacks is List) {
        for (final raw in rawCallbacks) {
          if (raw is! Map<String, dynamic>) continue;
          final name = raw['name'];
          final req = raw['request_type'];
          final resp = raw['response_type'];
          if (name is String && req is String && resp is String) {
            callbacks.add(
              RustCallbackMeta(
                name: name,
                requestType: req,
                responseType: resp,
              ),
            );
          }
        }
      }
    }
  }

  final String? crateName = crateNames.length == 1 ? crateNames.first : null;

  // attempt to infer the initialization helper from the bridge file, if it
  // exists. the bridge is generated by flutter_rust_bridge and lives next to
  // the metadata in `lib/src/rust/api`.
  String? initFnName;
  String? bridgeText;
  try {
    final bridgeFile = File('lib/src/rust/api/isolated_channels_bridge.dart');
    if (bridgeFile.existsSync()) {
      final text = await bridgeFile.readAsString();
      bridgeText = text;
      final match = RegExp(
        r'Future<\s*void\s*>\s*(init[^\(\s]+)\(',
      ).firstMatch(text);
      if (match != null) initFnName = match.group(1);
    }
  } catch (_) {
    // best effort; ignore failures
  }

  if (events.isEmpty && callbacks.isEmpty && bridgeText != null) {
    _inferChannelsFromBridge(bridgeText, events: events, callbacks: callbacks);
  }

  return RustChannelMetadata(
    events: events,
    callbacks: callbacks,
    crateName: crateName,
    initFnName: initFnName,
  );
}

void _inferChannelsFromBridge(
  String text, {
  required List<RustEventChannelMeta> events,
  required List<RustCallbackMeta> callbacks,
}) {
  final eventRegex = RegExp(
    r'Stream<\s*([A-Za-z0-9_]+)\s*>\s+([A-Za-z0-9_]+)Stream\s*\(',
  );
  for (final match in eventRegex.allMatches(text)) {
    final eventType = match.group(1);
    final baseName = match.group(2);
    if (eventType == null || baseName == null) continue;
    if (eventType.endsWith('PendingRequest')) continue;
    if (baseName.toLowerCase().contains('duplex')) continue;
    final name = _upperCamel(baseName);
    events.add(RustEventChannelMeta(name: name, eventType: eventType));
  }

  final callbackRegex = RegExp(
    r'Stream<\s*([A-Za-z0-9_]+PendingRequest)\s*>\s+([A-Za-z0-9_]+)RequestsStream\s*\(',
  );
  for (final match in callbackRegex.allMatches(text)) {
    final pendingType = match.group(1);
    final baseName = match.group(2);
    if (pendingType == null || baseName == null) continue;
    final name = _upperCamel(baseName);
    final requestType = _findRequestType(text, pendingType);
    final responseType = _findResponseType(text, baseName);
    if (requestType == null || responseType == null) continue;
    callbacks.add(
      RustCallbackMeta(
        name: name,
        requestType: requestType,
        responseType: responseType,
      ),
    );
  }
}

String? _findRequestType(String text, String pendingType) {
  final regex = RegExp(
    'class\\s+$pendingType\\s*\\{[\\s\\S]*?final\\s+([A-Za-z0-9_]+)\\s+request;',
  );
  return regex.firstMatch(text)?.group(1);
}

String? _findResponseType(String text, String baseName) {
  final regex = RegExp(
    'Future<\\s*void\\s*>\\s+${baseName}Respond\\s*\\(\\s*\\{[\\s\\S]*?required\\s+([A-Za-z0-9_]+)\\s+response',
  );
  return regex.firstMatch(text)?.group(1);
}

final class RoutePageBinding {
  const RoutePageBinding({
    required this.kindKey,
    required this.widgetType,
    required this.libraryUri,
  });

  final String kindKey;
  final String widgetType;
  final String libraryUri;
}

Future<RustRouteMetadata> readRustRouteMetadata() async {
  final dir = Directory('rust/target/oxide_routes');
  if (!dir.existsSync()) {
    return RustRouteMetadata(crateName: 'unknown', routes: const []);
  }

  final targetCrateName = _readCargoPackageName();
  final routes = <RustRouteMeta>[];

  final files = dir
      .listSync(followLinks: false)
      .whereType<File>()
      .where((f) => f.path.endsWith('.json'))
      .toList(growable: false);

  for (final file in files) {
    final jsonStr = await file.readAsString();
    final obj = jsonDecode(jsonStr);
    if (obj is! Map<String, dynamic>) continue;

    final fileCrate = obj['crate_name'];
    if (targetCrateName != null &&
        fileCrate is String &&
        fileCrate != targetCrateName) {
      continue;
    }
    // crate name from metadata is ignored

    final rawRoutes = obj['routes'];
    if (rawRoutes is! List) continue;

    for (final raw in rawRoutes) {
      if (raw is! Map<String, dynamic>) continue;
      final kind = raw['kind'];
      final rustType = raw['rust_type'];
      final path = raw['path'];
      final returnType = raw['return_type'];
      final extraType = raw['extra_type'];
      final rawFields = raw['fields'];

      if (kind is! String || kind.isEmpty) continue;
      if (rustType is! String || rustType.isEmpty) continue;

      final fields = <RustRouteFieldMeta>[];
      if (rawFields is List) {
        for (final f in rawFields) {
          if (f is! Map<String, dynamic>) continue;
          final name = f['name'];
          final type = f['ty'];
          if (name is String && type is String) {
            fields.add(RustRouteFieldMeta(name: name, type: type));
          }
        }
      }

      routes.add(
        RustRouteMeta(
          kind: kind,
          rustType: rustType,
          path: path is String ? path : null,
          returnType: returnType is String
              ? returnType
              : 'oxide_core::navigation::NoReturn',
          extraType: extraType is String
              ? extraType
              : 'oxide_core::navigation::NoExtra',
          fields: fields,
        ),
      );
    }
  }

  final byKind = <String, RustRouteMeta>{};
  for (final r in routes) {
    final existing = byKind[r.kind];
    if (existing == null) {
      byKind[r.kind] = r;
      continue;
    }
    if (!_sameRouteMeta(existing, r)) {
      throw StateError(
        'Conflicting route metadata for kind "${r.kind}" under rust/target/oxide_routes',
      );
    }
  }

  final dedupedRoutes = byKind.values.toList(growable: false)
    ..sort((a, b) => a.kind.compareTo(b.kind));
  // crateName isn’t tracked now; fall back to the Cargo package name or unknown
  return RustRouteMetadata(
    crateName: targetCrateName ?? 'unknown',
    routes: dedupedRoutes,
  );
}

Future<List<RoutePageBinding>> discoverRoutePages(BuildStep buildStep) async {
  final bindings = <RoutePageBinding>[];

  final package = buildStep.inputId.package;
  final byKindKey = <String, (RoutePageBinding, int)>{};
  final annotationRe = RegExp(r'@OxideRoutePage\s*\(\s*([^\)\r\n]+?)\s*\)');
  final classRe = RegExp(r'\bclass\s+([A-Za-z_]\w*)');
  final partOfRe = RegExp(r'^\s*part\s+of\b', multiLine: true);
  final routeCtorRe = RegExp(r'required\s+this\.route\b');
  final routeFieldRe = RegExp(r'\bfinal\s+[A-Za-z_]\w*Route\s+route\s*;');

  await for (final assetId in buildStep.findAssets(Glob('lib/**.dart'))) {
    if (assetId.package != package) continue;
    if (assetId.path.startsWith('lib/oxide_generated/')) continue;
    if (assetId.path.endsWith('.g.dart')) continue;

    final src = await buildStep.readAsString(assetId);
    if (partOfRe.hasMatch(src)) continue;

    final libraryUri = Uri(
      scheme: 'package',
      path: '$package/${assetId.path.substring('lib/'.length)}',
    ).toString();

    for (final annMatch in annotationRe.allMatches(src)) {
      final kindKey = _routeKindKeyFromSource(annMatch.group(1) ?? '');
      if (kindKey == null || kindKey.isEmpty) continue;

      final afterAnn = src.substring(annMatch.end);
      final classMatch = classRe.firstMatch(afterAnn);
      if (classMatch == null) continue;

      final widgetType = classMatch.group(1) ?? '';
      if (widgetType.isEmpty) continue;

      final classStart = annMatch.end + classMatch.start;
      final classSnippetEnd = (classStart + 2500) < src.length
          ? (classStart + 2500)
          : src.length;
      final classSnippet = src.substring(classStart, classSnippetEnd);
      final hasRouteCtor = routeCtorRe.hasMatch(classSnippet);
      final hasRouteField = routeFieldRe.hasMatch(classSnippet);
      final isLikelyPage =
          hasRouteCtor || hasRouteField || widgetType.endsWith('Page');
      if (!isLikelyPage) continue;

      var score = 0;
      if (widgetType.endsWith('Page')) score += 2;
      if (hasRouteCtor) score += 2;
      if (hasRouteField) score += 2;
      if (widgetType.endsWith('Screen')) score -= 1;

      final binding = RoutePageBinding(
        kindKey: kindKey,
        widgetType: widgetType,
        libraryUri: libraryUri,
      );
      final existing = byKindKey[kindKey];
      if (existing == null) {
        byKindKey[kindKey] = (binding, score);
        continue;
      }
      if (score > existing.$2) {
        byKindKey[kindKey] = (binding, score);
        continue;
      }
      if (score == existing.$2) {
        throw StateError(
          'Duplicate @OxideRoutePage binding for "$kindKey": ${existing.$1.widgetType} and ${binding.widgetType}',
        );
      }
    }
  }

  for (final entry in byKindKey.values) {
    bindings.add(entry.$1);
  }
  bindings.sort((a, b) => a.kindKey.compareTo(b.kindKey));
  return bindings;
}

String generateRouteKindSource(RustRouteMetadata metadata) {
  if (metadata.routes.isEmpty) {
    final buf = StringBuffer()
      ..writeln('// Generated by oxide_generator. Do not edit.')
      ..writeln()
      ..writeln('enum RouteKind {')
      ..writeln('  unknown,')
      ..writeln('}')
      ..writeln()
      ..writeln('extension RouteKindX on RouteKind {')
      ..writeln("  String get asStr => switch (this) {")
      ..writeln("    RouteKind.unknown => 'Unknown',")
      ..writeln('  };')
      ..writeln()
      ..writeln('  static RouteKind? fromStr(String s) => null;')
      ..writeln('}');

    return _formatter.format(buf.toString());
  }

  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    ..writeln('enum RouteKind {');

  for (final r in metadata.routes) {
    buf.writeln('  ${_lowerCamel(r.kind)},');
  }

  buf
    ..writeln('}')
    ..writeln()
    ..writeln('extension RouteKindX on RouteKind {')
    ..writeln("  String get asStr => switch (this) {");

  for (final r in metadata.routes) {
    final v = _lowerCamel(r.kind);
    buf.writeln("    RouteKind.$v => '${r.kind}',");
  }

  buf
    ..writeln('  };')
    ..writeln()
    ..writeln('  static RouteKind? fromStr(String s) => switch (s) {');

  for (final r in metadata.routes) {
    final v = _lowerCamel(r.kind);
    buf.writeln("    '${r.kind}' => RouteKind.$v,");
  }

  buf
    ..writeln('    _ => null,')
    ..writeln('  };')
    ..writeln('}');

  return _formatter.format(buf.toString());
}

String generateRouteModelsSource(RustRouteMetadata metadata) {
  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    ..writeln("import 'route_kind.g.dart';")
    ..writeln()
    ..writeln('abstract interface class OxideRoute {')
    ..writeln('  RouteKind get kind;')
    ..writeln('  Map<String, dynamic> toJson();')
    ..writeln('}')
    ..writeln();

  for (final r in metadata.routes) {
    final className = r.rustType;
    buf.writeln('final class $className implements OxideRoute {');
    if (r.fields.isEmpty) {
      buf.writeln('  const $className();');
    } else {
      buf.writeln('  const $className({');
      for (final f in r.fields) {
        buf.writeln('    required this.${_lowerCamel(f.name)},');
      }
      buf.writeln('  });');
    }
    buf.writeln();
    if (r.fields.isNotEmpty) {
      for (final f in r.fields) {
        final dartType = _dartTypeFromRust(f.type);
        buf.writeln('  final $dartType ${_lowerCamel(f.name)};');
      }
      buf.writeln();
    }
    buf.writeln('  @override');
    buf.writeln('  RouteKind get kind => RouteKind.${_lowerCamel(r.kind)};');
    buf.writeln();
    buf.writeln('  factory $className.fromJson(Map<String, dynamic> json) {');
    if (r.fields.isEmpty) {
      buf.writeln('    return const $className();');
    } else {
      buf.writeln('    return $className(');
      for (final f in r.fields) {
        final name = _lowerCamel(f.name);
        final dartType = _dartTypeFromRust(f.type);
        buf.writeln("      $name: json['$name'] as $dartType,");
      }
      buf.writeln('    );');
    }
    buf.writeln('  }');
    buf.writeln();
    buf.writeln('  @override');
    buf.writeln('  Map<String, dynamic> toJson() {');
    if (r.fields.isEmpty) {
      buf.writeln('    return const <String, dynamic>{};');
    } else {
      buf.writeln('    return <String, dynamic>{');
      for (final f in r.fields) {
        final name = _lowerCamel(f.name);
        buf.writeln("      '$name': $name,");
      }
      buf.writeln('    };');
    }
    buf.writeln('  }');
    buf.writeln('}');
    buf.writeln();
  }

  return _formatter.format(buf.toString());
}

String generateRouteBuildersSource(
  RustRouteMetadata metadata,
  List<RoutePageBinding> bindings,
) {
  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import '../routes/route_kind.g.dart';")
    ..writeln("import '../routes/route_models.g.dart';")
    ..writeln()
    ..writeln(
      'typedef OxideRouteBuilder = Widget Function(BuildContext context, OxideRoute route);',
    )
    ..writeln()
    ..writeln(
      'final Map<RouteKind, OxideRouteBuilder> oxideRouteBuilders = <RouteKind, OxideRouteBuilder>{',
    );

  final byKind = <String, RoutePageBinding>{};
  for (final b in bindings) {
    byKind[b.kindKey] = b;
  }

  for (final r in metadata.routes) {
    final kindKey = _lowerCamel(r.kind);
    final kindExpr = 'RouteKind.$kindKey';
    final binding = byKind[kindKey];
    if (binding == null) {
      buf.writeln(
        '  $kindExpr: (context, route) => throw UnimplementedError('
        "'Missing @OxideRoutePage mapping for $kindExpr'),",
      );
      continue;
    }
    buf.writeln('  $kindExpr: (context, route) {');
    buf.writeln('    final r = route as ${r.rustType};');
    buf.writeln('    return ${binding.widgetType}(route: r);');
    buf.writeln('  },');
  }

  buf.writeln('};');

  final raw = buf.toString();
  final importLines =
      bindings.map((b) => b.libraryUri).toSet().toList(growable: false)..sort();
  if (importLines.isEmpty) {
    return _formatter.format(raw);
  }

  final insertAfter = "import '../routes/route_models.g.dart';";
  final insertion = importLines.map((u) => "import '$u';").join('\n');
  return _formatter.format(
    raw.replaceFirst(insertAfter, '$insertAfter\n$insertion'),
  );
}

String generateNavigationRuntimeSource(RustRouteMetadata metadata) {
  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    ..writeln("import 'dart:async';")
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:oxide_runtime/oxide_runtime.dart';")
    ..writeln()
    ..writeln("import 'route_builders.g.dart';")
    ..writeln("import '../routes/route_kind.g.dart';")
    ..writeln("import '../routes/route_models.g.dart' as route_models;")
    ..writeln()
    ..writeln("import '../../src/rust/routes.dart' as rust_routes;")
    ..writeln(
      "import '../../src/rust/routes/oxide_navigation.dart' as rust_nav;",
    );

  final rustRouteImports =
      metadata.routes
          .map(
            (r) =>
                "import '../../src/rust/routes/${_snakeCase(r.rustType)}.dart';",
          )
          .toSet()
          .toList(growable: false)
        ..sort();
  for (final importLine in rustRouteImports) {
    buf.writeln(importLine);
  }
  buf.writeln();
  buf.writeln(
    'final GlobalKey<NavigatorState> oxideNavigatorKey = GlobalKey<NavigatorState>();',
  );
  buf.writeln();
  buf.writeln(
    'final NavigatorNavigationHandler<route_models.OxideRoute, RouteKind> oxideNavigationHandler = '
    'NavigatorNavigationHandler<route_models.OxideRoute, RouteKind>(',
  );
  buf.writeln('  navigatorKey: oxideNavigatorKey,');
  buf.writeln('  kindOf: (r) => r.kind,');
  buf.writeln('  routeBuilders: oxideRouteBuilders,');
  buf.writeln(');');
  buf.writeln();

  buf
    ..writeln(
      'route_models.OxideRoute _fromRustRoutePayload(rust_routes.RoutePayload payload) {',
    )
    ..writeln('  return payload.when(');

  for (final r in metadata.routes) {
    final rustType = r.rustType;
    final kindCtor = _lowerCamel(r.kind);
    buf.writeln('    $kindCtor: (field0) => route_models.$rustType(');
    for (final f in r.fields) {
      final fieldName = _lowerCamel(f.name);
      buf.writeln('      $fieldName: field0.$fieldName,');
    }
    buf.writeln('    ),');
  }
  buf
    ..writeln('  );')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'rust_routes.RoutePayload _toRustRoutePayload(route_models.OxideRoute route) {',
    )
    ..writeln('  switch (route.kind) {');

  for (final r in metadata.routes) {
    final rustType = r.rustType;
    final kindCtor = _lowerCamel(r.kind);
    buf.writeln('    case RouteKind.$kindCtor:');
    if (r.fields.isEmpty) {
      buf.writeln(
        '      return rust_routes.RoutePayload.$kindCtor($rustType());',
      );
    } else {
      buf.writeln('      final r = route as route_models.$rustType;');
      buf.writeln('      return rust_routes.RoutePayload.$kindCtor($rustType(');
      for (final f in r.fields) {
        final fieldName = _lowerCamel(f.name);
        buf.writeln('        $fieldName: r.$fieldName,');
      }
      buf.writeln('      ));');
    }
  }
  buf
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('RouteKind? _routeKindFromStr(String kind) {')
    ..writeln('  return switch (kind) {');

  for (final r in metadata.routes) {
    final kindCtor = _lowerCamel(r.kind);
    buf.writeln("    '${r.kind}' => RouteKind.$kindCtor,");
  }
  buf
    ..writeln('    _ => null,')
    ..writeln('  };')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'OxideNavigationCommand<route_models.OxideRoute, RouteKind> _mapOxideNavCommand(rust_nav.OxideNavCommand cmd) {',
    )
    ..writeln('  assert(() {')
    ..writeln('    // debug incoming commands from Rust')
    ..writeln('    // ignore: avoid_print')
    ..writeln('    print("[Oxide] received nav command: \$cmd");')
    ..writeln('    return true;')
    ..writeln('  }());')
    ..writeln('  return cmd.when(')
    ..writeln('    push: (route, ticket) {')
    ..writeln('      final decoded = _fromRustRoutePayload(route);')
    ..writeln(
      '      return OxideNavigationCommand.push(route: decoded, ticket: ticket);',
    )
    ..writeln('    },')
    ..writeln('    pop: (resultJson) {')
    ..writeln(
      '      final Object? result = resultJson == null ? null : jsonDecode(resultJson);',
    )
    ..writeln('      return OxideNavigationCommand.pop(result: result);')
    ..writeln('    },')
    ..writeln('    popUntil: (kind) {')
    ..writeln('      final routeKind = _routeKindFromStr(kind);')
    ..writeln(
      "      if (routeKind == null) throw StateError('Unknown route kind: \$kind');",
    )
    ..writeln('      return OxideNavigationCommand.popUntil(kind: routeKind);')
    ..writeln('    },')
    ..writeln('    reset: (routes) {')
    ..writeln('      final decoded = <route_models.OxideRoute>[];')
    ..writeln('      for (final r in routes) {')
    ..writeln('        decoded.add(_fromRustRoutePayload(r));')
    ..writeln('      }')
    ..writeln('      return OxideNavigationCommand.reset(routes: decoded);')
    ..writeln('    },')
    ..writeln('  );')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'final OxideNavigationRuntime<route_models.OxideRoute, RouteKind> oxideNavigationRuntime = '
      'OxideNavigationRuntime<route_models.OxideRoute, RouteKind>(',
    )
    ..writeln('  commands: rust_nav.oxideNavCommandsStream()')
    ..writeln('      .map(_mapOxideNavCommand)')
    ..writeln(
      '      .cast<OxideNavigationCommand<route_models.OxideRoute, RouteKind>>(),',
    )
    ..writeln('  handler: oxideNavigationHandler,')
    ..writeln('  kindOf: (route) => route.kind,')
    ..writeln(
      '  emitResult: (ticket, result) => rust_nav.oxideNavEmitResult('
      'ticket: ticket, resultJson: jsonEncode(result)),',
    )
    ..writeln(
      '  setCurrentRoute: (route) => rust_nav.oxideNavSetCurrentRoute('
      'route: route == null ? null : _toRustRoutePayload(route)),',
    )
    ..writeln(');')
    ..writeln()
    ..writeln(
      '// start the navigation runtime once; repeat calls are benign but',
    )
    ..writeln(
      '// this prevents excessive stream subscriptions when init is invoked',
    )
    ..writeln('// multiple times (e.g. hot-restart, debug experiments).')
    // top-level flag keeps state across repeated init calls; easier to format
    ..writeln('bool _oxideNavStarted = false;')
    ..writeln('Future<void> oxideNavStart() async {')
    ..writeln('  assert(() {')
    ..writeln('    // debug log to trace calls')
    ..writeln('    // ignore: avoid_print')
    ..writeln(
      r"    print('[Oxide] oxideNavStart called, started=$_oxideNavStarted');",
    )
    ..writeln('    return true;')
    ..writeln('  }());')
    ..writeln('  if (_oxideNavStarted) return;')
    ..writeln('  _oxideNavStarted = true;')
    ..writeln('  oxideNavigationRuntime.start();')
    ..writeln('  WidgetsBinding.instance.addPostFrameCallback((_) {')
    ..writeln(
      '    // initNavigation requires the navigation stack to exist (after the first frame).',
    )
    ..writeln('    unawaited(rust_nav.initNavigation());')
    ..writeln('  });')
    ..writeln('}')
    ..writeln()
    ..writeln('Future<void> oxideNavStop() => oxideNavigationRuntime.stop();');

  return _formatter.format(buf.toString());
}

String generateOxideStackSource({RustChannelMetadata? channels}) {
  // only import the bridge helpers when the Rust code actually defines
  // events or callbacks that will be referenced below. otherwise the file
  // doesn't exist and builds will fail (see example todos_app).
  final hasChannels =
      channels != null &&
      (channels.events.isNotEmpty || channels.callbacks.isNotEmpty);
  final initFnName = channels?.initFnName;

  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:oxide_runtime/oxide_runtime.dart';")
    ..writeln();
  if (hasChannels) {
    // alias the bridge so we can continue to call methods without prefixing.
    buf.writeln(
      "import '../src/rust/api/isolated_channels_bridge.dart' as channels;",
    );
    // some types generated by the bridge (notably the pending-request objects)
    // are defined in the same file but we'd like to expose them unprefixed in
    // the public APIs below. import them explicitly with `show` so the class
    // names are available without `_ch.` qualifiers.
    if (channels.callbacks.isNotEmpty == true) {
      final pendingNames = channels.callbacks
          .map((c) => '${c.name}PendingRequest')
          .toSet()
          .join(', ');
      buf.writeln(
        'import "../src/rust/api/isolated_channels_bridge.dart" show $pendingNames;',
      );
    }
    // also bring in any channel type definitions; frb_generated.dart only imports
    // these files, it doesn't export their symbols, so other libraries won't
    // see them. importing channels.dart directly ensures event/callback types
    // like `CounterDemoEvent` are available to downstream code.
    buf.writeln("import '../src/rust/isolated_channels_demo/channels.dart';");
    // in addition, some helper types (e.g. *PendingRequest) live in the
    // platform-specific generated file rather than the base. the conditional
    // import inside frb_generated.dart sometimes confuses the analyzer, so we
    // pull in the io variant explicitly; analysis of web builds may still
    // succeed since those files export the same names.
    buf.writeln(
      "import '../src/rust/frb_generated.io.dart'; // ignore: unused_import",
    );
    buf.writeln();
  }
  buf
    ..writeln("import '../src/rust/frb_generated.dart';")
    ..writeln()
    ..writeln("import 'navigation/navigation_runtime.g.dart';")
    ..writeln("import 'routes/route_kind.g.dart';")
    ..writeln("import 'routes/route_models.g.dart';")
    ..writeln()
    ..writeln('final class OxideStack {')
    ..writeln('  static bool _initialized = false;')
    ..writeln()
    ..writeln('  static bool get isInitialized => _initialized;')
    ..writeln()
    ..writeln(
      '  static GlobalKey<NavigatorState> get navigatorKey => oxideNavigatorKey;',
    )
    ..writeln()
    ..writeln(
      '  static Future<void> init({bool startNavigation = false}) async {',
    )
    ..writeln('    if (_initialized) return;')
    ..writeln(
      '    // make sure flutter bindings are ready; simplifies example setup',
    )
    ..writeln('    WidgetsFlutterBinding.ensureInitialized();')
    ..writeln('    await RustLib.init();')
    ..writeln(
      '    _initialized = true;',
    ) // when channels are generated we need to make sure they are initialized too;
    // running this inside the common startup path frees consumers from having
    // to remember to call a channel helper by hand.
    ..writeln(
      hasChannels
          ? '    // initialize any generated channel APIs before returning'
          : '',
    )
    ..writeln(hasChannels ? '    await oxideInitChannels();' : '')
    ..writeln('    if (startNavigation) {')
    ..writeln('      await oxideNavStart();')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln()
    ..writeln('  // navigation runtime is already generated')
    ..writeln(
      '  static OxideNavigationRuntime<OxideRoute, RouteKind> get navigation {',
    )
    ..writeln('    _ensureInitialized();')
    ..writeln('    return oxideNavigationRuntime;')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  // central stub for any generated event APIs. concrete channels will be',
    )
    ..writeln(
      '  // added here by the generator when events are declared in Rust.',
    )
    ..writeln('  static OxideEvents get events => _events;')
    ..writeln('  static final _events = OxideEvents._();')
    ..writeln()
    ..writeln(
      '  // central stub for any generated callback APIs. methods will be added',
    )
    ..writeln(
      '  // here by generator when callback interfaces are declared in Rust.',
    )
    ..writeln('  static OxideCallbacks get callbacks => _callbacks;')
    ..writeln('  static final _callbacks = OxideCallbacks._();')
    ..writeln()
    ..writeln('  static void _ensureInitialized() {')
    ..writeln('    if (_initialized) return;')
    ..writeln(
      "    throw StateError('OxideStack.init() must be called from main() before using Oxide APIs.');",
    )
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln(
      '// placeholders that allow upstream code to append members when channels',
    )
    ..writeln(
      '// or callback systems are generated. the classes are intentionally private',
    )
    ..writeln(
      '// because consumers should only interact via the typed getters above, which',
    )
    ..writeln('// can later hide nullability or initialization details.')
    ..writeln('final class OxideEvents {')
    ..writeln('  const OxideEvents._();')
    ..writeln('');
  // emit channel getters if metadata available
  if (channels != null && channels.events.isNotEmpty) {
    for (final e in channels.events) {
      final field = _lowerCamel(e.name);
      buf.writeln('  // event channel for ${e.name}');
      buf.writeln('  Stream<${e.eventType}> get $field =>');
      buf.writeln('      channels.${field}Stream();');
      buf.writeln();
    }
  } else {
    buf.writeln('  // generated members will be injected here');
  }
  buf.writeln('}');
  buf.writeln();
  buf.writeln('final class OxideCallbacks {');
  buf.writeln('  const OxideCallbacks._();');
  buf.writeln('');
  // callbacks
  if (channels != null && channels.callbacks.isNotEmpty) {
    for (final c in channels.callbacks) {
      final method = _lowerCamel(c.name);
      buf.writeln('  // callback service for ${c.name}');
      buf.writeln('  Stream<${c.name}PendingRequest> get ${method}Requests =>');
      buf.writeln('      channels.${method}RequestsStream();');
      buf.writeln();
      buf.writeln(
        '  Future<void> ${method}Respond({required BigInt id, required ${c.responseType} response}) =>',
      );
      buf.writeln(
        '      channels.${method}Respond(id: id, response: response);',
      );
      buf.writeln();
    }
  } else {
    buf.writeln('  // generated members will be injected here');
  }
  buf.writeln('}');

  // helper that initializes any generated channel APIs. the name of the
  // underlying function is derived from the crate name supplied by the
  // channel metadata; when the crate name is unavailable we still emit an
  // empty stub so that callers can always invoke `oxideInitChannels` without
  // conditional logic.
  if (hasChannels) {
    buf.writeln('');
    buf.writeln('Future<void> oxideInitChannels() async {');
    if (initFnName != null) {
      buf.writeln('  await channels.$initFnName();');
    } else {
      buf.writeln(
        '  // no-op; failed to determine the generated init helper name',
      );
    }
    buf.writeln('}');
  }
  // convenience helper for example applications to remove boilerplate
  buf.writeln('');
  buf.writeln('// helper that initializes Oxide and starts the Flutter app');
  buf.writeln(
    '// navigation startup is deferred until the first frame so that the',
  );
  buf.writeln(
    '// navigator key is attached before commands are processed; this avoids',
  );
  buf.writeln(
    '// spurious resets / flicker when the runtime immediately emits the',
  );
  buf.writeln('// initial route.');
  buf.writeln(
    'Future<void> runOxideApp(Widget app, {bool startNavigation = true}) async {',
  );
  buf.writeln('  WidgetsFlutterBinding.ensureInitialized();');
  buf.writeln(
    '  // always perform core init; navigation start is deferred until the first frame.',
  );
  buf.writeln('  await OxideStack.init();');
  buf.writeln('  runApp(app);');
  buf.writeln('  if (startNavigation) {');
  buf.writeln('    WidgetsBinding.instance.addPostFrameCallback((_) {');
  buf.writeln('      oxideNavStart();');
  buf.writeln('    });');
  buf.writeln('  }');
  buf.writeln('}');
  return _formatter.format(buf.toString());
}

String generateOxideEntrypointSource({bool includeSrcOxide = false}) {
  final buf = StringBuffer()
    ..writeln('// Generated by oxide_generator. Do not edit.')
    ..writeln()
    // expose the core entrypoint and conveniently export the app helper too
    ..writeln(
      "export 'oxide_generated/oxide_stack.g.dart' show OxideStack, runOxideApp;",
    )
    ..writeln(
      "export 'oxide_generated/routes/route_kind.g.dart' show RouteKind, RouteKindX;",
    )
    ..writeln("export 'oxide_generated/routes/route_models.g.dart';");

  if (includeSrcOxide) {
    buf
      ..writeln()
      ..writeln(
        '// re-export example-specific helpers so consumers can use the',
      )
      ..writeln('// package root rather than dipping into src/.')
      ..writeln("export 'src/oxide.dart';");
  }

  return _formatter.format(buf.toString());
}

String _lowerCamel(String s) {
  if (s.isEmpty) return s;
  final parts = s
      .split(RegExp(r'[_\-\s]+'))
      .where((p) => p.isNotEmpty)
      .toList(growable: false);
  if (parts.isEmpty) return s;

  final first = parts.first;
  final firstLower = first[0].toLowerCase() + first.substring(1);
  if (parts.length == 1) return firstLower;

  final rest = parts
      .skip(1)
      .map((p) => p.isEmpty ? p : (p[0].toUpperCase() + p.substring(1)))
      .join();
  return '$firstLower$rest';
}

String _upperCamel(String s) {
  if (s.isEmpty) return s;
  final lower = _lowerCamel(s);
  if (lower.isEmpty) return lower;
  return lower[0].toUpperCase() + lower.substring(1);
}

String _snakeCase(String s) {
  if (s.isEmpty) return s;
  final withUnderscores = s.replaceAllMapped(
    RegExp(r'(?<!^)([A-Z])'),
    (m) => '_${m[1]}',
  );
  return withUnderscores.toLowerCase();
}

String _dartTypeFromRust(String rustType) {
  final normalized = rustType.replaceAll(' ', '');
  final optionMatch = RegExp(r'^Option<(.+)>$').firstMatch(normalized);
  if (optionMatch != null) {
    return '${_dartTypeFromRust(optionMatch.group(1)!)}?';
  }
  final vecMatch = RegExp(r'^Vec<(.+)>$').firstMatch(normalized);
  if (vecMatch != null) {
    return 'List<${_dartTypeFromRust(vecMatch.group(1)!)}>';
  }
  final boxMatch = RegExp(r'^(Box|Arc|Rc)<(.+)>$').firstMatch(normalized);
  if (boxMatch != null) {
    return _dartTypeFromRust(boxMatch.group(2)!);
  }
  final mapMatch = RegExp(r'^(HashMap|BTreeMap)<(.+)>$').firstMatch(normalized);
  if (mapMatch != null) {
    final args = _splitRustGenericArgs(mapMatch.group(2)!);
    if (args.length == 2) {
      return 'Map<${_dartTypeFromRust(args[0])}, ${_dartTypeFromRust(args[1])}>';
    }
  }
  final base = _stripRustPath(normalized);
  switch (base) {
    case 'String':
    case 'str':
      return 'String';
    case 'bool':
      return 'bool';
    case 'f32':
    case 'f64':
      return 'double';
    case 'i8':
    case 'i16':
    case 'i32':
    case 'isize':
    case 'u8':
    case 'u16':
    case 'u32':
    case 'usize':
      return 'int';
    case 'i64':
    case 'u64':
    case 'i128':
    case 'u128':
      return 'BigInt';
    default:
      return base;
  }
}

String _stripRustPath(String s) {
  final parts = s.split('::');
  return parts.isEmpty ? s : parts.last;
}

List<String> _splitRustGenericArgs(String s) {
  final args = <String>[];
  final buf = StringBuffer();
  var depth = 0;
  for (var i = 0; i < s.length; i++) {
    final ch = s[i];
    if (ch == '<') depth++;
    if (ch == '>') depth--;
    if (ch == ',' && depth == 0) {
      args.add(buf.toString());
      buf.clear();
      continue;
    }
    buf.write(ch);
  }
  if (buf.isNotEmpty) {
    args.add(buf.toString());
  }
  return args
      .map((a) => a.trim())
      .where((a) => a.isNotEmpty)
      .toList(growable: false);
}

String? _readCargoPackageName() {
  final file = File('rust/Cargo.toml');
  if (!file.existsSync()) return null;
  final lines = file.readAsLinesSync();
  var inPackage = false;
  for (final raw in lines) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    if (line.startsWith('[') && line.endsWith(']')) {
      inPackage = line == '[package]';
      continue;
    }
    if (!inPackage) continue;
    if (!line.startsWith('name')) continue;
    final parts = line.split('=');
    if (parts.length < 2) continue;
    final value = parts.sublist(1).join('=').trim();
    final trimmed = value.replaceAll('"', '').replaceAll("'", '');
    if (trimmed.isNotEmpty) return trimmed;
  }
  return null;
}

bool _sameRouteMeta(RustRouteMeta a, RustRouteMeta b) {
  if (a.kind != b.kind) return false;
  if (a.rustType != b.rustType) return false;
  if (a.path != b.path) return false;
  if (a.returnType != b.returnType) return false;
  if (a.extraType != b.extraType) return false;
  if (a.fields.length != b.fields.length) return false;
  for (var i = 0; i < a.fields.length; i++) {
    final af = a.fields[i];
    final bf = b.fields[i];
    if (af.name != bf.name) return false;
    if (af.type != bf.type) return false;
  }
  return true;
}

String? _routeKindKeyFromSource(String expr) {
  final s = expr.trim();
  if (s.isEmpty) return null;

  final strMatch = RegExp(r"""^(['"])(.*)\1$""").firstMatch(s);
  if (strMatch != null) {
    final raw = strMatch.group(2) ?? '';
    if (raw.isEmpty) return null;
    return _lowerCamel(raw);
  }

  final enumMatch = RegExp(r'^RouteKind\.([A-Za-z_]\w*)$').firstMatch(s);
  if (enumMatch != null) {
    final raw = enumMatch.group(1) ?? '';
    if (raw.isEmpty) return null;
    return _lowerCamel(raw);
  }

  return null;
}
