// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/comments_bridge.dart';
import '../frb_generated.dart';
import '../routes.dart';
import 'home_route.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'splash_route.dart';
import 'user_detail_route.dart';
part 'oxide_navigation.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `__oxide_nav_call_init`, `__oxide_nav_call_on_route_change`, `__oxide_nav_require_fresh_frb_bindings`, `map_nav_command`, `map_route_operation`, `nav_route_to_route_payload`, `parse_optional_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> initNavigation() =>
    RustLib.instance.api.crateRoutesOxideNavigationInitNavigation();

Stream<OxideNavCommand> oxideNavCommandsStream() =>
    RustLib.instance.api.crateRoutesOxideNavigationOxideNavCommandsStream();

Future<void> oxideNavEmitResult({
  required String ticket,
  required String resultJson,
}) => RustLib.instance.api.crateRoutesOxideNavigationOxideNavEmitResult(
  ticket: ticket,
  resultJson: resultJson,
);

Future<void> oxideNavSetCurrentRoute({RoutePayload? route}) => RustLib
    .instance
    .api
    .crateRoutesOxideNavigationOxideNavSetCurrentRoute(route: route);

Future<void> oxideNavRouteUpdate({required RouteUpdateContext update}) =>
    RustLib.instance.api.crateRoutesOxideNavigationOxideNavRouteUpdate(
      update: update,
    );

@freezed
sealed class OxideNavCommand with _$OxideNavCommand {
  const OxideNavCommand._();

  const factory OxideNavCommand.push({
    required RoutePayload route,
    String? ticket,
  }) = OxideNavCommand_Push;
  const factory OxideNavCommand.pop({String? resultJson}) = OxideNavCommand_Pop;
  const factory OxideNavCommand.popUntil({required String kind}) =
      OxideNavCommand_PopUntil;
  const factory OxideNavCommand.reset({required List<RoutePayload> routes}) =
      OxideNavCommand_Reset;
}
