import 'package:flutter/foundation.dart';

/// ANSI color codes for terminal output
class AnsiColors {
  static const reset = '\x1B[0m';
  static const red = '\x1B[31m';
  static const green = '\x1B[32m';
  static const yellow = '\x1B[33m';
  static const blue = '\x1B[34m';
  static const magenta = '\x1B[35m';
  static const cyan = '\x1B[36m';
  static const white = '\x1B[37m';
  static const gray = '\x1B[90m';
}

enum LogLevel { trace, debug, info, warn, error }

/// A unified, zero-cost (in release) logger for the Oxide framework
class OxideLogger {
  /// Defines if debugging is entirely stripped by the AOT compiler.
  /// If `false`, trace and debug calls are completely removed in release builds.
  static const bool _isLogEnabled = bool.fromEnvironment('OXIDE_DEBUG_LOGS', defaultValue: false);

  /// Enables verbose transition payload logs (before/action/after).
  static const bool _isAdvancedLogEnabled = bool.fromEnvironment('ENABLE_ADVANCED_LOGS', defaultValue: false);

  /// Helper to determine if we should log based on mode and flag
  static bool get _shouldLog => !kReleaseMode || _isLogEnabled;

  /// `true` only when logging is active and advanced payload logs are enabled.
  static bool get isAdvancedLoggingEnabled => _shouldLog && _isAdvancedLogEnabled;

  static void _log(LogLevel level, String source, String message, {Object? error, StackTrace? stackTrace}) {
    if (!_shouldLog) return;

    final String color;
    final String levelStr;

    switch (level) {
      case LogLevel.trace:
        color = AnsiColors.gray;
        levelStr = 'TRC';
        break;
      case LogLevel.debug:
        color = AnsiColors.blue;
        levelStr = 'DBG';
        break;
      case LogLevel.info:
        color = AnsiColors.green;
        levelStr = 'INF';
        break;
      case LogLevel.warn:
        color = AnsiColors.yellow;
        levelStr = 'WRN';
        break;
      case LogLevel.error:
        color = AnsiColors.red;
        levelStr = 'ERR';
        break;
    }

    final timestamp = DateTime.now().toIso8601String().split('T').last;

    // Format: [12:34:56.789] [TRC] [Source] Message
    final buffer = StringBuffer();
    buffer.write('$color[$timestamp] [$levelStr] ');
    buffer.write(AnsiColors.magenta);
    buffer.write('[$source] ');
    buffer.write(color);
    buffer.write(message);

    if (error != null) {
      buffer.write('\nError: $error');
    }
    if (stackTrace != null) {
      buffer.write('\n$stackTrace');
    }
    buffer.write(AnsiColors.reset);

    debugPrint(buffer.toString());
  }

  static void trace(String source, String message) => _log(LogLevel.trace, source, message);
  static void debug(String source, String message) => _log(LogLevel.debug, source, message);
  static void info(String source, String message) => _log(LogLevel.info, source, message);
  static void warn(String source, String message, [Object? error, StackTrace? stackTrace]) =>
      _log(LogLevel.warn, source, message, error: error, stackTrace: stackTrace);
  static void error(String source, String message, [Object? error, StackTrace? stackTrace]) =>
      _log(LogLevel.error, source, message, error: error, stackTrace: stackTrace);

  /// Verbose transition logging for payload-aware debugging.
  static void advancedTransition(String source, {required Object? before, required Object? action, required Object? after}) {
    if (!isAdvancedLoggingEnabled) return;
    _log(LogLevel.trace, source, 'State transition: before=$before -> action=$action -> after=$after');
  }

  /// Verbose diagnostics logging for payload-aware debugging.
  static void advanced(String source, String message) {
    if (!isAdvancedLoggingEnabled) return;
    _log(LogLevel.trace, source, message);
  }

  /// Attach a stream of Rust logs generated by `setup_rust_logs` FFI binding.
  static void attachRustStream(Stream<(String, String, String)> rustLogStream) {
    if (!_shouldLog) return;
    rustLogStream.listen((event) {
      handleRustLog(event.$1, event.$2, event.$3);
    });
  }

  /// Handle incoming logs from the Rust core
  static void handleRustLog(String level, String target, String message) {
    if (!_shouldLog) return;

    LogLevel parsedLevel;
    switch (level.toLowerCase()) {
      case 'trace':
        parsedLevel = LogLevel.trace;
        break;
      case 'debug':
        parsedLevel = LogLevel.debug;
        break;
      case 'info':
        parsedLevel = LogLevel.info;
        break;
      case 'warn':
        parsedLevel = LogLevel.warn;
        break;
      case 'error':
        parsedLevel = LogLevel.error;
        break;
      default:
        parsedLevel = LogLevel.info;
        break;
    }

    _log(parsedLevel, 'Rust:$target', message);
  }
}
