// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'common.freezed.dart';

@freezed
sealed class LoadPhase with _$LoadPhase {
  const LoadPhase._();

  const factory LoadPhase.idle() = LoadPhase_Idle;
  const factory LoadPhase.loading() = LoadPhase_Loading;
  const factory LoadPhase.ready() = LoadPhase_Ready;
  const factory LoadPhase.error({required String message}) = LoadPhase_Error;
}
