// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'comments_action.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

@freezed
sealed class CommentsAction with _$CommentsAction {
  const CommentsAction._();

  const factory CommentsAction.loadForPost({required BigInt postId}) =
      CommentsAction_LoadForPost;
  const factory CommentsAction.refresh() = CommentsAction_Refresh;
}
