// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Post {
  final BigInt id;
  final BigInt userId;
  final String title;

  const Post({required this.id, required this.userId, required this.title});

  @override
  int get hashCode => id.hashCode ^ userId.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Post &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          title == other.title;
}

///oxide:state
///oxide:meta:{"kind":"state","name":"PostsState","docs":[],"fields":[{"name":"phase","ty":"LoadPhase"},{"name":"posts","ty":"Vec < Post >"},{"name":"selected_user_id","ty":"Option < u64 >"},{"name":"selected_post_id","ty":"Option < u64 >"}],"variants":null}
class PostsState {
  final LoadPhase phase;
  final List<Post> posts;
  final BigInt? selectedUserId;
  final BigInt? selectedPostId;

  const PostsState({
    required this.phase,
    required this.posts,
    this.selectedUserId,
    this.selectedPostId,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      posts.hashCode ^
      selectedUserId.hashCode ^
      selectedPostId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostsState &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          posts == other.posts &&
          selectedUserId == other.selectedUserId &&
          selectedPostId == other.selectedPostId;
}
