// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'posts_action.freezed.dart';

@freezed
sealed class PostsAction with _$PostsAction {
  const PostsAction._();

  const factory PostsAction.loadForUser({required BigInt userId}) =
      PostsAction_LoadForUser;
  const factory PostsAction.refresh() = PostsAction_Refresh;
  const factory PostsAction.selectPost({required BigInt postId}) =
      PostsAction_SelectPost;
}
