// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'routes/home_route.dart';
import 'routes/splash_route.dart';
import 'routes/user_detail_route.dart';
part 'routes.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_kind_and_payload`, `payload_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_str`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `hash`, `into_payload`, `into_payload`, `into_payload`, `kind`

enum RouteKind {
  home,
  splash,
  userDetail;

  Future<void> asStr() =>
      RustLib.instance.api.crateRoutesRouteKindAsStr(that: this);

  static Future<RouteKind?> fromStr({required String s}) =>
      RustLib.instance.api.crateRoutesRouteKindFromStr(s: s);
}

@freezed
sealed class RoutePayload with _$RoutePayload {
  const RoutePayload._();

  const factory RoutePayload.home(HomeRoute field0) = RoutePayload_Home;
  const factory RoutePayload.splash(SplashRoute field0) = RoutePayload_Splash;
  const factory RoutePayload.userDetail(UserDetailRoute field0) =
      RoutePayload_UserDetail;

  Future<RouteKind> kind() =>
      RustLib.instance.api.crateRoutesRoutePayloadKind(that: this);
}
