// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// State for the ticker example.
///oxide:state
///oxide:meta:{"kind":"state","name":"AppState","docs":["frb_encoded(235b667262286e6f6e5f6f7061717565295d)","State for the ticker example."],"fields":[{"name":"ticks","ty":"u64"},{"name":"is_running","ty":"bool"},{"name":"interval_ms","ty":"u64"},{"name":"last_tick_source","ty":"String"}],"variants":null}
class AppState {
  /// Number of ticks observed so far.
  final BigInt ticks;

  /// Whether auto ticking is currently enabled.
  final bool isRunning;

  /// Tick interval used by the auto ticker (milliseconds).
  final BigInt intervalMs;

  /// Most recent tick source (`auto`, `manual`, or `side_effect`).
  final String lastTickSource;

  const AppState({
    required this.ticks,
    required this.isRunning,
    required this.intervalMs,
    required this.lastTickSource,
  });

  @override
  int get hashCode =>
      ticks.hashCode ^
      isRunning.hashCode ^
      intervalMs.hashCode ^
      lastTickSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppState &&
          runtimeType == other.runtimeType &&
          ticks == other.ticks &&
          isRunning == other.isRunning &&
          intervalMs == other.intervalMs &&
          lastTickSource == other.lastTickSource;
}
