// Generated by oxide_generator. Do not edit.

enum RouteKind {
  home,
  splash,
}

extension RouteKindX on RouteKind {
  String get name => switch (this) {
        RouteKind.home => 'Home',
        RouteKind.splash => 'Splash',
      };
}
