import 'dart:async';

import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:oxide_runtime/oxide_runtime.dart';

import 'rust/api/bridge.dart' show ArcAppEngine, AppStateSnapshot, createEngine, current, dispatch, disposeEngine, stateStream;

// public facade generated by oxide_generator
export '../oxide_generated/oxide_stack.g.dart' show OxideStack;

// re-export channel bridge APIs and channel types so downstream code only imports oxide.dart
export 'package:counter_app/src/rust/api/isolated_channels_bridge.dart';
export 'package:counter_app/src/rust/isolated_channels_demo/channels.dart';

// state imports (must appear before any declarations)
import 'rust/state/app_action.dart';
import 'rust/state/app_state.dart';
// channel types needed for wrapper signatures
import 'package:counter_app/src/rust/isolated_channels_demo/channels.dart';

// private alias for wrappers
// ignore: no_leading_underscores_for_library_prefixes
import 'package:counter_app/src/rust/api/isolated_channels_bridge.dart' as _ch;

// public aliases for types defined in bridge (so callers don't see `_ch` prefix)
part 'oxide.oxide.g.dart';

typedef CounterDemoDialogPendingRequest = _ch.CounterDemoDialogPendingRequest;

// convenience wrappers mirroring the bridge API so consumers don't need a
// separate import. names are intentionally identical to keep examples simple.

/// Send a notification from Rust to Dart.
Future<void> emitCounterDemoNotification({required String message}) => _ch.emitCounterDemoNotification(message: message);

/// Stream of demo events (Rust → Dart).
///
/// **Deprecated**: use `OxideStack.events.counterDemoEvents` instead. This
/// helper remains to avoid immediate breaking changes in examples.
@Deprecated('use OxideStack.events.counterDemoEvents')
Stream<CounterDemoEvent> counterDemoEventsStream() => _ch.counterDemoEventsStream();

/// Stream of callback requests (Rust → Dart).
///
/// **Deprecated**: use `OxideStack.callbacks.counterDemoDialogRequests`.
@Deprecated('use OxideStack.callbacks.counterDemoDialogRequests')
Stream<_ch.CounterDemoDialogPendingRequest> counterDemoDialogRequestsStream() => _ch.counterDemoDialogRequestsStream();

/// Send a callback response (Dart → Rust).
///
/// **Deprecated**: use `OxideStack.callbacks.counterDemoDialogRespond`.
@Deprecated('use OxideStack.callbacks.counterDemoDialogRespond')
Future<void> counterDemoDialogRespond({required BigInt id, required CounterDemoDialogResponse response}) =>
    _ch.counterDemoDialogRespond(id: id, response: response);

/// Request confirmation from Dart.
Future<bool> counterDemoDialogConfirm({required String title}) => _ch.counterDemoDialogConfirm(title: title);

/// Request confirmation using FRB callback helper.
Future<bool> counterDemoDialogConfirmViaFrbCallback({required String title, required FutureOr<bool> Function(String) dartConfirm}) =>
    _ch.counterDemoDialogConfirmViaFrbCallback(title: title, dartConfirm: dartConfirm);

/// Duplex helpers
Stream<CounterDemoOut> counterDemoDuplexOutgoingStream() => _ch.counterDemoDuplexOutgoingStream();
Future<void> counterDemoDuplexSend({required String text}) => _ch.counterDemoDuplexSend(text: text);
Future<void> counterDemoDuplexIncoming({required CounterDemoIn event}) => _ch.counterDemoDuplexIncoming(event: event);
Future<String?> counterDemoLastIncomingText() => _ch.counterDemoLastIncomingText();

/// Oxide setup for this example:
/// - Declares the Rust engine + state/actions/snapshot types.
/// - Enables dev-only codegen (run build_runner) to generate:
///   - a ChangeNotifier controller
///   - an Actions facade
///   - a widget scope with a `useOxide(context)` accessor
@OxideStore(
  state: AppState,
  snapshot: AppStateSnapshot,
  actions: AppAction,
  engine: ArcAppEngine,
  backend: OxideBackend.inherited,
  keepAlive: true,
  name: 'StateBridgeOxide',
)
class StateBridgeOxide {}

@OxideStore(
  state: AppState,
  snapshot: AppStateSnapshot,
  actions: AppAction,
  engine: ArcAppEngine,
  backend: OxideBackend.inheritedHooks,
  keepAlive: true,
  name: 'StateBridgeHooksOxide',
)
class StateBridgeHooksOxide {}

@OxideStore(
  state: AppState,
  snapshot: AppStateSnapshot,
  actions: AppAction,
  engine: ArcAppEngine,
  backend: OxideBackend.riverpod,
  keepAlive: true,
  name: 'StateBridgeRiverpodOxide',
)
class StateBridgeRiverpodOxide {}

@OxideStore(
  state: AppState,
  snapshot: AppStateSnapshot,
  actions: AppAction,
  engine: ArcAppEngine,
  backend: OxideBackend.bloc,
  keepAlive: true,
  name: 'StateBridgeBlocOxide',
)
class StateBridgeBlocOxide {}
