// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

///oxide:state
///oxide:meta:{"kind":"state","name":"Theme","docs":[],"fields":null,"variants":[{"name":"Light","docs":[],"fields":[]},{"name":"Dark","docs":[],"fields":[]}]}
enum Theme {
  light,
  dark;

  static Future<List<ThemeSlice>> inferSlicesImpl({
    required Theme before,
    required Theme after,
  }) => RustLib.instance.api.crateConfigEnumsThemeTypeThemeInferSlicesImpl(
    before: before,
    after: after,
  );
}

enum ThemeSlice { oxideUnused }
