// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_url_lock`

Future<String> apiBaseUrl() => RustLib.instance.api.crateApiBridgeApiBaseUrl();

Future<void> initOxide() => RustLib.instance.api.crateApiBridgeInitOxide();

Future<void> setApiBaseUrl({required String url}) =>
    RustLib.instance.api.crateApiBridgeSetApiBaseUrl(url: url);

Future<String> getApiBaseUrl() =>
    RustLib.instance.api.crateApiBridgeGetApiBaseUrl();

Future<void> resetApiBaseUrl() =>
    RustLib.instance.api.crateApiBridgeResetApiBaseUrl();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< OxideError>>
abstract class OxideError implements RustOpaqueInterface {}
