// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state/comments_action.dart';
import '../state/comments_state.dart';
import '../state/common.dart';
import 'bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CommentsReducer`, `CommentsSideEffect`, `__OxideReducerMarker_CommentsReducer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `effect`, `fmt`, `from`, `init`, `reduce`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `dispatch`, `new`, `subscribe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ArcCommentsEngine> createEngine() =>
    RustLib.instance.api.crateApiCommentsBridgeCreateEngine();

Future<void> disposeEngine({required ArcCommentsEngine engine}) =>
    RustLib.instance.api.crateApiCommentsBridgeDisposeEngine(engine: engine);

Future<CommentsStateSnapshot> dispatch({
  required ArcCommentsEngine engine,
  required CommentsAction action,
}) => RustLib.instance.api.crateApiCommentsBridgeDispatch(
  engine: engine,
  action: action,
);

Future<CommentsStateSnapshot> current({required ArcCommentsEngine engine}) =>
    RustLib.instance.api.crateApiCommentsBridgeCurrent(engine: engine);

Stream<CommentsStateSnapshot> stateStream({
  required ArcCommentsEngine engine,
}) => RustLib.instance.api.crateApiCommentsBridgeStateStream(engine: engine);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Arc < CommentsEngine >>>
abstract class ArcCommentsEngine implements RustOpaqueInterface {}

class CommentsStateSnapshot {
  final BigInt revision;
  final CommentsState state;

  const CommentsStateSnapshot({required this.revision, required this.state});

  @override
  int get hashCode => revision.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentsStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state;
}
