// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state/common.dart';
import '../state/users_action.dart';
import '../state/users_state.dart';
import 'bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UsersReducer`, `UsersSideEffect`, `__OxideReducerMarker_UsersReducer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `effect`, `fmt`, `from`, `init`, `reduce`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `dispatch`, `new`, `subscribe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ArcUsersEngine> createEngine() =>
    RustLib.instance.api.crateApiUsersBridgeCreateEngine();

Future<void> disposeEngine({required ArcUsersEngine engine}) =>
    RustLib.instance.api.crateApiUsersBridgeDisposeEngine(engine: engine);

Future<UsersStateSnapshot> dispatch({
  required ArcUsersEngine engine,
  required UsersAction action,
}) => RustLib.instance.api.crateApiUsersBridgeDispatch(
  engine: engine,
  action: action,
);

Future<UsersStateSnapshot> current({required ArcUsersEngine engine}) =>
    RustLib.instance.api.crateApiUsersBridgeCurrent(engine: engine);

Stream<UsersStateSnapshot> stateStream({required ArcUsersEngine engine}) =>
    RustLib.instance.api.crateApiUsersBridgeStateStream(engine: engine);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Arc < UsersEngine >>>
abstract class ArcUsersEngine implements RustOpaqueInterface {}

class UsersStateSnapshot {
  final BigInt revision;
  final UsersState state;

  const UsersStateSnapshot({required this.revision, required this.state});

  @override
  int get hashCode => revision.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UsersStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state;
}
