// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../channels.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `__oxide_require_fresh_event_stream_bindings`

Stream<ShowcaseDemoEvent> oxideEventsStream() => RustLib.instance.api
    .crateIsolatedChannelsDemoChannelsOxideIsolatedEventsShowcaseDemoEventsFrbOxideEventsStream();
