// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state/app_action.dart';
import '../state/app_state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_ticker_thread`, `start`, `stop_ticker_thread`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppRootReducer`, `AppSideEffect`, `_TickerTask`, `__OxideReducerMarker_AppRootReducer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `effect`, `from`, `init`, `reduce`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `dispatch`, `new`, `subscribe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ArcAppEngine> createEngine() =>
    RustLib.instance.api.crateApiBridgeCreateEngine();

Future<void> disposeEngine({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeDisposeEngine(engine: engine);

Future<AppStateSnapshot> dispatch({
  required ArcAppEngine engine,
  required AppAction action,
}) =>
    RustLib.instance.api.crateApiBridgeDispatch(engine: engine, action: action);

Future<AppStateSnapshot> current({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeCurrent(engine: engine);

Stream<AppStateSnapshot> stateStream({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeStateStream(engine: engine);

Future<void> initOxide() => RustLib.instance.api.crateApiBridgeInitOxide();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Arc < AppEngine >>>
abstract class ArcAppEngine implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< OxideError>>
abstract class OxideError implements RustOpaqueInterface {}

class AppStateSnapshot {
  final BigInt revision;
  final AppState state;

  const AppStateSnapshot({required this.revision, required this.state});

  @override
  int get hashCode => revision.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state;
}
