// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state/app_action.dart';
import '../state/app_state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_ticker_thread`, `increment_tick`, `start`, `stop_ticker_thread`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppRootReducer`, `AppSideEffect`, `_TickerTask`, `__OxideReducerMarker_AppRootReducer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `effect`, `from`, `infer_slices`, `init`, `reduce`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `dispatch`, `new`, `subscribe`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<ArcAppEngine> createEngine() =>
    RustLib.instance.api.crateApiBridgeCreateEngine();

Future<void> disposeEngine({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeDisposeEngine(engine: engine);

Future<AppStateSnapshot> dispatch({
  required ArcAppEngine engine,
  required AppAction action,
}) =>
    RustLib.instance.api.crateApiBridgeDispatch(engine: engine, action: action);

Future<AppStateSnapshot> current({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeCurrent(engine: engine);

Stream<AppStateSnapshot> stateStream({required ArcAppEngine engine}) =>
    RustLib.instance.api.crateApiBridgeStateStream(engine: engine);

/// Initializes the Oxide runtime for this example.
///
/// Call this once during app startup (after `RustLib.init()` on the Dart side)
/// before creating any engines.
///
/// # Examples
/// ```
/// use rust_lib_ticker_app::api::bridge::init_oxide;
///
/// tokio::runtime::Runtime::new()
///     .unwrap()
///     .block_on(async { init_oxide().await.unwrap() });
/// ```
Future<void> initOxide() => RustLib.instance.api.crateApiBridgeInitOxide();

Future<ArcAppEngine> createSharedEngine() =>
    RustLib.instance.api.crateApiBridgeCreateSharedEngine();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Arc < AppEngine >>>
abstract class ArcAppEngine implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< OxideError>>
abstract class OxideError implements RustOpaqueInterface {}

class AppStateSnapshot {
  final BigInt revision;
  final AppState state;
  final List<AppStateSlice> slices;

  const AppStateSnapshot({
    required this.revision,
    required this.state,
    required this.slices,
  });

  @override
  int get hashCode => revision.hashCode ^ state.hashCode ^ slices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state &&
          slices == other.slices;
}
