// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../isolated_channels_demo/channels.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> initIsolatedChannelsDemo() => RustLib.instance.api
    .crateApiIsolatedChannelsBridgeInitIsolatedChannelsDemo();

Future<void> emitShowcaseDemoNotification({required String message}) => RustLib
    .instance
    .api
    .crateApiIsolatedChannelsBridgeEmitShowcaseDemoNotification(
      message: message,
    );

Stream<ShowcaseDemoEvent> showcaseDemoEventsStream() => RustLib.instance.api
    .crateApiIsolatedChannelsBridgeShowcaseDemoEventsStream();

Stream<ShowcaseDemoDialogPendingRequest> showcaseDemoDialogRequestsStream() =>
    RustLib.instance.api
        .crateApiIsolatedChannelsBridgeShowcaseDemoDialogRequestsStream();

Future<void> showcaseDemoDialogRespond({
  required BigInt id,
  required ShowcaseDemoDialogResponse response,
}) => RustLib.instance.api
    .crateApiIsolatedChannelsBridgeShowcaseDemoDialogRespond(
      id: id,
      response: response,
    );

Future<bool> showcaseDemoDialogConfirm({required String title}) => RustLib
    .instance
    .api
    .crateApiIsolatedChannelsBridgeShowcaseDemoDialogConfirm(title: title);

Stream<ShowcaseDemoOut> showcaseDemoDuplexOutgoingStream() => RustLib
    .instance
    .api
    .crateApiIsolatedChannelsBridgeShowcaseDemoDuplexOutgoingStream();

Future<void> showcaseDemoDuplexSend({required String text}) => RustLib
    .instance
    .api
    .crateApiIsolatedChannelsBridgeShowcaseDemoDuplexSend(text: text);

Future<void> showcaseDemoDuplexIncoming({required ShowcaseDemoIn event}) =>
    RustLib.instance.api
        .crateApiIsolatedChannelsBridgeShowcaseDemoDuplexIncoming(event: event);

Future<String?> showcaseDemoLastIncomingText() => RustLib.instance.api
    .crateApiIsolatedChannelsBridgeShowcaseDemoLastIncomingText();

class ShowcaseDemoDialogPendingRequest {
  final BigInt id;
  final ShowcaseDemoDialogRequest request;

  const ShowcaseDemoDialogPendingRequest({
    required this.id,
    required this.request,
  });

  @override
  int get hashCode => id.hashCode ^ request.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShowcaseDemoDialogPendingRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          request == other.request;
}
